import org.codehaus.groovy.runtime.MethodClosure

import java.util.function.Consumer

//Setup project extension so builds that apply the script can actually call the functions
ext.addProjectJars = this.&addProjectJars as MethodClosure
ext.classpathCompile = this.&classpathCompile as MethodClosure
ext.classpathRuntime = this.&classpathRuntime as MethodClosure
ext.combinedProjects = this.&combinedProjects as MethodClosure
ext.commonMavenArtifact = this.&commonMavenArtifact as MethodClosure
ext.createJarTasks = this.&createJarTasks as MethodClosure
ext.extendFrom = this.&extendFrom as MethodClosure
ext.extendRunnable = this.&extendRunnable as MethodClosure
ext.fabricVersion = this.&fabricVersion as MethodClosure
ext.forgeVersion = this.&forgeVersion as MethodClosure
ext.getArchiveTaskFile = this.&getArchiveTaskFile as MethodClosure
ext.getArchiveTask = this.&getArchiveTask as MethodClosure
ext.getJavaVersion = this.&getJavaVersion as MethodClosure
ext.getParentPath = this.&getParentPath as MethodClosure
ext.getProjectJavaVersion = this.&getProjectJavaVersion as MethodClosure
ext.getProjectList = this.&getProjectList as MethodClosure
ext.getProjectListFrom = this.&getProjectListFrom as MethodClosure
ext.getProjectProperty = this.&getProjectProperty as MethodClosure
ext.getTaskPath = this.&getTaskPath as MethodClosure
ext.getTaskOutputs = this.&getTaskOutputs as MethodClosure
ext.inheritCompileSources = this.&inheritCompileSources as MethodClosure
ext.inheritResources = this.&inheritResources as MethodClosure
ext.invokeOnProject = this.&invokeOnProject as MethodClosure
ext.isCleanroom = this.&isCleanroomProject as MethodClosure
ext.isJava8 = this.&isJava8 as MethodClosure
ext.isJava17 = this.&isJava17 as MethodClosure
ext.isJava21 = this.&isJava21 as MethodClosure
ext.isLegacyProject = this.&isLegacyProject as MethodClosure
ext.isLoaderBase = this.&isLoaderBase as MethodClosure
ext.isMinorVersion = this.&isMinorVersion as MethodClosure
ext.isNeoforgeCompatible = this.&isNeoforgeCompatible as MethodClosure
ext.isProjectCleanroom = this.&isProjectCleanroom as MethodClosure
ext.isProjectJava8 = this.&isProjectJava8 as MethodClosure
ext.isProjectJava17 = this.&isProjectJava17 as MethodClosure
ext.isProjectJava21 = this.&isProjectJava21 as MethodClosure
ext.isProjectLegacy = this.&isProjectLegacy as MethodClosure
ext.isProjectLoaderBase = this.&isProjectLoaderBase as MethodClosure
ext.isProjectMinorVersion = this.&isProjectMinorVersion as MethodClosure
ext.isProjectNeoforgeCompatible = this.&isProjectNeoforgeCompatible as MethodClosure
ext.isProjectRunnable = this.&isProjectRunnable as MethodClosure
ext.isProjectShared = this.&isProjectShared as MethodClosure
ext.isRunnableProject = this.&isRunnableProject as MethodClosure
ext.isSharedProject = this.&isSharedProject as MethodClosure
ext.javaSources = this.&javaSources as MethodClosure
ext.minecraftVersion = this.&minecraftVersion as MethodClosure
ext.modsBundle = this.&modsBundle as MethodClosure
ext.neoforgeVersion = this.&neoforgeVersion as MethodClosure
ext.parchmentVersion = this.&parchmentVersion as MethodClosure
ext.projectMCVersion = this.&projectMCVersion as MethodClosure
ext.propertyString = this.&propertyString as MethodClosure
ext.rootFile = this.&rootFile as MethodClosure
ext.setDev = this.&setDev as MethodClosure
ext.setLoaderConfigs = this.&setLoaderConfigs as MethodClosure
ext.setJarsRunAfter = this.&setJarsRunAfter as MethodClosure
ext.setSharedDependencies = this.&setSharedDependencies as MethodClosure
ext.setSharedShadowJar = this.&setSharedShadowJar as MethodClosure
ext.setRepositories = this.&setRepositories as MethodClosure
ext.sourceSetOf = this.&sourceSetOf as MethodClosure
ext.sourceSetOutput = this.&sourceSetOutput as MethodClosure
ext.uniminedCore = this.&uniminedCore as MethodClosure
ext.uniminedCommon = this.&uniminedCommon as MethodClosure
ext.uniminedFabric = this.&uniminedFabric as MethodClosure
ext.uniminedForge = this.&uniminedForge as MethodClosure
ext.uniminedNeoforge = this.&uniminedNeoforge as MethodClosure
ext.withMCVersion = this.&withMCVersion as MethodClosure

void addProjectJars(String ... p_names) {
    jar {
        p_names.each {p_name ->
            from(getArchiveTaskFile(project(p_name), 'jar').collect {entry ->
                zipTree entry
            })
        }
    }
}

static FileCollection classpathCompile(Project project, String source_name) {
    return sourceSetOf(project,source_name).compileClasspath
}

static FileCollection classpathRuntime(Project project, String source_name) {
    return sourceSetOf(project,source_name).runtimeClasspath
}

static List<Project> combinedProjects(Project project) {
    return project.getProjectList(isProjectLoaderBase(project) ? [ ':api' ] : [ ':api', ':shared' ])
}

static Consumer<RepositoryHandler> commonMavenArtifact(Project project, String id) {
    Consumer<RepositoryHandler> consumer = handler -> {
        def maven_data = commonMavenData id
        int size = maven_data.size()
        if(size>1) {
            handler.maven {
                name = maven_data.get(0)
                url = project.uri "https://${maven_data.get(1)}"
                if(size>2) {
                    def included_groups = maven_data.subList(2,maven_data.size())
                    //noinspection GrUnresolvedAccess
                    content {
                        included_groups.forEach {grp ->
                            //noinspection GrUnresolvedAccess
                            includeGroup grp
                        }
                    }
                }
            }
        }
    }
    return consumer
}

@SuppressWarnings('GroovyFallthrough')
private static List<String> commonMavenData(String id) {
    switch(id) {
        case 'blamejared': case 'bookshelf': case 'crafttweaker': case 'ct': case 'darkhax': case 'gamestages':
        case 'jared': case 'zencode': case 'zen':
            return [ 'BlameJared', 'maven.blamejared.com', 'com.blamejared.crafttweaker', 'net.darkhax.bookshelf',
              'net.darkhax.gamestages', 'org.openzen.zencode' ]
        case 'cf': case 'curse': case 'curseforge': case 'cursemaven':
            return [ 'CurseMaven', 'curse.cleanroommc.com/', 'curse.maven' ]
        case 'cleanroom': case 'hei':
            return [ 'CleanroomMC', 'maven.cleanroommc.com', 'mezz' ]
        case 'fast': case 'fastutil': case 'sonatype':
            return [ 'SonaType', 'oss.sonatype.org/content/repositories/public/', 'it.unimi.dsi' ]
        case 'jei': case 'modmaven':
            return [ 'ModMaven', 'modmaven.dev', 'mezz.jei' ]
        case 'legacy': case 'moddinglegacy':
            return [ 'Modding Legacy', 'maven.moddinglegacy.com/maven', 'com.legacy' ]
        case 'modrinth':
            return [ 'Modrinth', 'api.modrinth.com/maven', 'maven.modrinth' ]
        case 'modmenu': case 'terraformers': case 'terraformersmc':
            return [ 'Terraformers', 'maven.terraformersmc.com/', 'com.terraformersmc' ]
        case 'nucleoid': case 'pb4': case 'placeholder':
            return [ 'Nucleoid', 'maven.nucleoid.xyz/', 'eu.pb4']
        default: return  []
    }
}

void createJarTasks(boolean neoforge) {
    def loaders = neoforge ? [ 'fabric', 'forge', 'neoforge' ] : [ 'fabric', 'forge' ]
    loaders.forEach {loader ->
        tasks.register("${loader}Jar", Jar) {jar_task ->
            jar_task.archiveClassifier.set "$loader"
            jar_task.from sourceSetOutput(project, loader)
        }
    }
}

void extendFrom(String file_name) {
    apply from: rootFile(project, "gradle\\scripts\\${file_name}.gradle")
}

void extendRunnable() {
    extendFrom "java${getJavaVersion()}-module"
}

String fabricVersion() {
    return withMCVersion('fabric')
}

String forgeVersion() {
    return withMCVersion('forge')
}

static Provider<RegularFile> getArchiveTaskFile(Project project, String task_name) {
    return getArchiveTask(project, task_name).archiveFile
}

static AbstractArchiveTask getArchiveTask(Project project, String task_name) {
    return project."$task_name"
}

int getJavaVersion() {
    return isJava8() ? 8 : (isJava21() ? 21 : 17)
}

static String getParentPath(String p_name) {
    int num_parents = p_name.count '.'
    switch(num_parents) {
        case 1: return "${p_name.split('_')[0]}"
        case 2: return "${p_name.split('_')[0]}${p_name.substring(0,p_name.length()-2)}"
        default: return 'cleanroom'==p_name ? ':legacy' : null
    }
}

static int getProjectJavaVersion(Project project) {
    return isProjectJava8(project) ? 8 : (isProjectJava21(project) ? 21 : 17)
}

List<Project> getProjectList(List<String> p_names) {
    return getProjectListFrom(project, p_names)
}

static List<Project> getProjectListFrom(Project reference, List<String> p_names) {
    return p_names.collect {p_name ->
        reference.project(p_name)
    }
}

static def getProjectProperty(Project project, String property_name) {
    return project."$property_name"
}

static String getTaskPath(String p_name, String task_name) {
    def parent_path = getParentPath(p_name)
    return parent_path==null ? "$p_name:$task_name" : "$parent_path:$p_name:$task_name"
}

static def getTaskOutputs(Project project, String task_name) {
    return project."$task_name".outputs
}

void inheritCompileSources(String ... parent_names) {
    compileJava {
        parent_names.each {parent_name ->
            source javaSources(project(parent_name), 'main')
        }
    }
    compileTestJava {
        parent_names.each {parent_name ->
            source javaSources(project(parent_name), 'test')
        }
    }
}

void inheritResources(String ... parent_names) {
    processResources {
        parent_names.each {parent_name ->
            from getTaskOutputs(project(parent_name), 'processResources')
        }
    }
    processTestResources {
        parent_names.each {parent_name ->
            from getTaskOutputs(project(parent_name), 'processTestResources')
        }
    }
}

static def invokeOnProject(Project project, String method_name) {
    return project."$method_name"()
}

boolean isCleanroomProject() {
    return 'cleanroom'==name
}

boolean isJava8() {
    return [ '1.12', 'api', 'fabric', 'forge', 'legacy', 'shared_1.16' ].contains(name)
}

boolean isJava17() {
    return !isJava8() && !isJava21()
}

boolean isJava21() {
    return [ 'cleanroom', 'shared_1.20.6', 'shared_1.21', 'shared_1.21.1' ].contains(name)
}

boolean isLegacyProject() {
    return [ '1.12', 'cleanroom' ].contains(name)
}

boolean isLoaderBase() {
    return [ 'fabric', 'forge', 'legacy', 'neoforge' ].contains(name)
}

boolean isMinorVersion() {
    return [ 'shared_1.19.2', 'shared_1.19.4', 'shared_1.20.1', 'shared_1.20.4', 'shared_1.20.6',
             'shared_1.21.1' ].contains(name)
}

boolean isNeoforgeCompatible() {
    return [ 'neoforge', 'shared_1.20', 'shared_1.20.4', 'shared_1.20.6', 'shared_1.21',
             'shared_1.21.1' ].contains(name)
}

static boolean isProjectCleanroom(Project project) {
    return invokeOnProject(project,'isCleanroomProject')
}

static boolean isProjectJava8(Project project) {
    return invokeOnProject(project,'isJava8')
}

static boolean isProjectJava17(Project project) {
    return invokeOnProject(project,'isJava17')
}

static boolean isProjectJava21(Project project) {
    return invokeOnProject(project,'isJava21')
}

static boolean isProjectLegacy(Project project) {
    return invokeOnProject(project,'isLegacyProject')
}

static boolean isProjectLoaderBase(Project project) {
    return invokeOnProject(project,'isLoaderBase')
}

static boolean isProjectMinorVersion(Project project) {
    return invokeOnProject(project,'isMinorVersion')
}

static boolean isProjectNeoforgeCompatible(Project project) {
    return invokeOnProject(project,'isNeoforgeCompatible')
}

static boolean isProjectRunnable(Project project) {
    return invokeOnProject(project,'isRunnableProject')
}

static boolean isProjectShared(Project project) {
    return invokeOnProject(project,'isSharedProject')
}

boolean isRunnableProject() {
    return [ '1.12', 'cleanroom', 'shared_1.16', 'shared_1.18', 'shared_1.19.2', 'shared_1.19.4', 'shared_1.20.1',
             'shared_1.20.4', 'shared_1.20.6', 'shared_1.21.1' ].contains(name)
}

boolean isSharedProject() {
    return [ 'shared', 'shared_1.16', 'shared_1.18', 'shared_1.19', 'shared_1.19.2', 'shared_1.19.4', 'shared_1.20',
             'shared_1.20.1', 'shared_1.20.4', 'shared_1.20.6', 'shared_1.21', 'shared_1.21.1' ].contains(name)
}

static SourceDirectorySet javaSources(Project project, String source_name) {
    return sourceSetOf(project, source_name).allJava
}

/**
 * Assumed the input project has a version association
 */
boolean mappingStyleOfficial() {
    return [ 'shared_1.20.6', 'shared_1.21', 'shared_1.21.1' ].contains(name)
}

String minecraftVersion() {
    return withMCVersion('minecraft')
}

Provider<ExternalModuleDependencyBundle> modsBundle(String loader, String type) {
    if(isLegacyProject()) return legacy.bundles.mods.'1'.'12'.'2'."$type"
    String[] mc = projectMCVersion().split '_'
    return project."$loader".bundles.mods.'1'."${mc[1]}"."${mc[2]}"."$type"
}

String neoforgeVersion() {
    return withMCVersion('neoforge')
}

String parchmentVersion() {
    return withMCVersion('parchment')
}

@SuppressWarnings('GroovyFallthrough')
String projectMCVersion() {
    switch(name) {
        case 'cleanroom':
        case 'legacy': return '1_12_2'
        case 'fabric':
        case 'forge': return '1_16_5'
        case 'neoforge': return '1_20_4'
        default: {
            String mc_version = name.split('_').last().replace('.','_')
            switch(mc_version) {
                case '1_12': return '1_12_2'
                case '1_16': return '1_16_5'
                case '1_18': return '1_18_2'
                case '1_19': return '1_19_2'
                case '1_20': return '1_20_1'
                case '1_21': return '1_21_1'
                default: return mc_version
            }
        }
    }
}

String propertyString(String name) {
    return String.valueOf(property(name))
}

static File rootFile(Project project, String path) {
    return project.rootProject.file(path)
}

void setDev() {
    configurations {
        dev {
            canBeResolved = false
            canBeConsumed = true
        }
    }
    artifacts {
        dev jar
    }
}

void setLoaderConfigs(boolean neoforge_compatible) {
    sourceSets {
        def main_output = sourceSetOutput(project, 'main')
        fabric {
            compileClasspath+=main_output
            runtimeClasspath+=main_output
        }
        forge {
            compileClasspath+=main_output
            runtimeClasspath+=main_output
        }
        if(neoforge_compatible) {
            neoforge {
                compileClasspath+=main_output
                runtimeClasspath+=main_output
            }
        }
    }
    createJarTasks neoforge_compatible
    configurations {
        fabric {
            canBeResolved = false
            canBeConsumed = true
        }
        forge {
            canBeResolved = false
            canBeConsumed = true
        }
        if(neoforge_compatible) {
            neoforge {
                canBeResolved = false
                canBeConsumed = true
            }
        }
    }
    artifacts {
        fabric fabricJar
        forge forgeJar
        if(neoforge_compatible) neoforge neoforgeJar
    }
}

void setJarsRunAfter(boolean finalized_by_shadow, String ... parent_names) {
    def build_tasks = parent_names.collect {parent_name ->
        getTaskPath(parent_name, 'build')
    }
    jar {
        if(isSharedProject()) {
            (isNeoforgeCompatible() ? [ 'fabric', 'forge', 'neoforge' ] : [ 'fabric', 'forge' ]).forEach {
                from(getArchiveTaskFile(project,"${it}Jar"))
            }
        }
        manifest {
            def attribute_map = [ 'Implementation-Title': mod_name, 'Implementation-Version': mod_version ]
            if(isLegacyProject()) attribute_map.putAll(['FMLCorePlugin': legacy_entrypoint,
                                                        'FMLCorePluginContainsFMLMod': true, 'ForceLoadAsMod': true])
            attributes(attribute_map)
        }
        build_tasks.forEach {build_task ->
            mustRunAfter build_task
        }
        if(finalized_by_shadow) finalizedBy 'shadowJar'
    }
    sourcesJar {
        build_tasks.forEach {build_task ->
            mustRunAfter build_task
        }
    }
}

void setSharedDependencies(String ... maven_ids) {
    setRepositories maven_ids
    dependencies {
        boolean minor_version = isMinorVersion()
        if(minor_version) compileOnlyApi parent
        if(isSharedProject()) {
            def versions = name.split('_')[1].split '\\.'
            def dep_provider = fabric.versions.api.'1'."${versions[1]}"
            if(versions.length==3) dep_provider = dep_provider."${versions[2]}"
            else dep_provider = dep_provider.asProvider()
            //noinspection GrUnresolvedAccess
            fabricImplementation fabricApi.fabric(dep_provider.get())
        }
        def types = isNeoforgeCompatible() ? [ 'fabric', 'forge', 'neoforge' ] : [ 'fabric', 'forge' ]
        boolean is_runnable = isRunnableProject()
        types.forEach {loader ->
            logger.lifecycle "Applying $loader-specific dependencies for $name"
            "${loader}CompileOnly" project(path: ":$loader", configuration: 'dev')
            if(is_runnable) {
                if(minor_version) {
                    "${loader}Implementation" parent
                    "${loader}Implementation" project(path: parent.path, configuration: "$loader")
                }
                if(isSharedProject() && project.parent!=null) {
                    "${loader}Implementation" libs.bundles.burningwave
                    "${loader}AnnotationProcessor" libs.lombok
                    "${loader}CompileOnly" libs.lombok
                }
                "${loader}Implementation" modsBundle(loader, 'implementation')
                "${loader}RuntimeOnly" modsBundle(loader, 'runtime')
            }
        }
    }
}

void setSharedShadowJar() {
    def shaded_projects = isLegacyProject() ? [ ':api', ':legacy' ] : [ ':api', ':fabric', ':forge', ':shared' ]
    if(isLegacyProject()) shaded_projects+=':legacy'
    else {
        shaded_projects.addAll([ 'fabric', 'forge', 'shared' ])
        if(isNeoforgeCompatible()) shaded_projects+=':neoforge'
        if(isMinorVersion()) shaded_projects+=project.parent.path
    }
    shadowJar {
        shaded_projects.each {p_name ->
            //noinspection GrUnresolvedAccess
            from(getArchiveTaskFile(project(p_name), 'jar').collect {entry ->
                zipTree entry
            })
        }
    }
    tasks.assemble.dependsOn shadowJar
}

void setRepositories(String ... maven_ids) {
    project.repositories {handler ->
        maven_ids.each {id ->
            if('central'==id) mavenCentral()
            else {
                def consumer = commonMavenArtifact project, id
                if(consumer!=null) consumer.accept handler
            }
        }
    }
}

static SourceSet sourceSetOf(Project project, String source_name) {
    return getProjectProperty(project, 'sourceSets')."$source_name"
}

static SourceSetOutput sourceSetOutput(Project project, String source_name) {
    return sourceSetOf(project, source_name).output
}

void uniminedCore(String loader_name, boolean is_runnable, List<String> args) {
    logger.lifecycle "Setting up core unimined stuff for $name"
    unimined.useGlobalCache = false
    unimined.minecraft {
        def mc_version = minecraftVersion()
        logger.lifecycle "Got unimined minecraft version for $name as $mc_version"
        version mc_version
        def combined = combinedProjects(project)
        combined.forEach {combined_project ->
            combineWith combined_project, sourceSetOf(combined_project, 'main')
        }
        mappings {
            if(isLegacyProject()) mcp 'stable', legacy_mappings_1_12_2
            else {
                boolean production_official_mappings = mappingStyleOfficial()
                if(!production_official_mappings) intermediary()
                mojmap()
                if(isJava8()) parchment mc_version, parchmentVersion()
                devNamespace 'mojmap'
            }
        }
        switch(loader_name) {
            case 'cleanroom': {
                cleanroom {
                    loader cleanroom_loader_version
                    if(is_runnable) {
                        runs.all {
                            systemProperty 'foundation.verbose', 'true'
                            if(!args.isEmpty()) jvmArgs args
                        }
                    }
                }
                break
            }
            case 'fabric': {
                fabric {
                    loader fabric_loader
                    if(is_runnable) {
                        runs.all {
                            systemProperty 'foundation.verbose', 'true'
                            if(!args.isEmpty()) jvmArgs args
                        }
                    }
                }
                break
            }
            case 'forge': {
                minecraftForge {
                    loader forgeVersion()
                    if(is_runnable) {
                        runs.all {
                            systemProperty 'foundation.verbose', 'true'
                            if(!args.isEmpty()) jvmArgs args
                        }
                    }
                }
                break
            }
            case 'neoforge': {
                neoForge {
                    loader neoforgeVersion()
                    if(is_runnable) {
                        runs.all {
                            systemProperty 'foundation.verbose', 'true'
                            if(!args.isEmpty()) jvmArgs args
                        }
                    }
                }
                break
            }
        }
        defaultRemapJar = false
    }
    logger.lifecycle "Finished setting up core unimined stuff for $name"
}

void uniminedCommon() {
    uniminedCore 'none', false, []
}

//TODO Figure out how to get fabric parents to work without causing version conflicts
@SuppressWarnings('GrUnresolvedAccess')
void uniminedFabric(boolean is_runnable) {
    unimined.minecraft(sourceSets.fabric) {
        combineWith sourceSets.main
        fabric {
            loader fabric_loader
            if(is_runnable) {
                runs.all {
                    systemProperty 'foundation.verbose', 'true'
                }
            }
        }
    }
}

//TODO Figure out how to get forge parents to work without causing version conflicts
@SuppressWarnings('GrUnresolvedAccess')
void uniminedForge(boolean is_runnable) {
    unimined.minecraft(sourceSets.forge) {
        combineWith sourceSets.main
        minecraftForge {
            loader forgeVersion()
            if(is_runnable) {
                runs.all {
                    systemProperty 'foundation.verbose', 'true'
                }
            }
        }
    }
}

//TODO Figure out how to get neoforge parents to work without causing version conflicts
@SuppressWarnings('GrUnresolvedAccess')
void uniminedNeoforge(boolean is_runnable) {
    unimined.minecraft(sourceSets.neoforge) {
        combineWith sourceSets.main
        neoForge {
            loader neoforgeVersion()
            if(is_runnable) {
                runs.all {
                    systemProperty 'foundation.verbose', 'true'
                }
            }
        }
    }
}

String withMCVersion(String type) {
    return propertyString("${type}_${projectMCVersion()}")
}