import static org.gradle.api.file.DuplicatesStrategy.EXCLUDE

plugins.apply 'idea'
plugins.apply 'java'
plugins.apply 'java-library'

group = base_package
version = mod_version

idea {
    module {
        downloadJavadoc = true
    }
}

java {
    withSourcesJar()
    withJavadocJar()
}

tasks.withType(JavaCompile).forEach {
    it.options.encoding = 'UTF-8'
    it.options.deprecation = false
}

tasks.withType(Jar).forEach {
    it.archiveBaseName = mod_id
    it.duplicatesStrategy = EXCLUDE
}

tasks.withType(ProcessResources).forEach {
    it.duplicatesStrategy = EXCLUDE
}