/**
 * Common builds and sources relevant to all Fabric modules. Based in 1.16.5
 */
plugins {
    alias libs.plugins.unimined
}

extendRunnable 8
extendFrom 'nonshaded-deps'

uniminedCore 'fabric', false, []

setDev()

dependencies {
    Provider<String> dep_provider = fabric.versions.api.'1'.'16'.'5'
    modImplementation fabricApi.fabric(dep_provider.get())
}

processResources {
    def replacements = [ 'adaptor': fabric_adaptor, 'injector': fabric_injector, 'version': version ]
    inputs.properties replacements
    from(project(':api').processResources.outputs) {
        filesMatching('fabric.mod.json') {copy_details ->
            expand replacements
        }
    }
}

processTestResources {
    from project(':api').processTestResources.outputs
}

jar {
    from(project(':api').jar.archiveFile.collect {entry ->
        zipTree entry
    })
    manifest {
        attributes([
                'Implementation-Title': mod_name,
                'Implementation-Version': mod_version
        ])
    }
}

setJarsRunAfter true, ':api'