//file:noinspection GroovyAssignabilityCheck

/**
 * Common builds and sources relevant to all Fabric modules
 *
 * Base is 1.16.5
 */

buildscript {
    repositories {
        gradlePluginPortal() {
            content {
                unimined_plugin_portal.split(';').each {grp ->
                    includeGroup grp
                }
            }
        }
        maven {
            name = 'WagYourMaven Releases'
            url = uri 'https://maven.wagyourtail.xyz/releases'
            content {
                unimined_releases.split(';').each {grp ->
                    includeGroup grp
                }
            }
        }
        maven {
            name = 'WagYourMaven Snapshots'
            url = uri 'https://maven.wagyourtail.xyz/snapshots'
            content {
                unimined_snapshots.split(';').each {grp ->
                    includeGroup grp
                }
            }
        }
    }
    dependencies {
        classpath "$shadow_plugin:$shadow_version"
        classpath "$unimined_plugin:$unimined_version"
    }
}

apply from: rootProject.file('gradle\\scripts\\java8-module.gradle')
apply from: rootProject.file('gradle\\scripts\\fabric.gradle')

plugins.apply 'xyz.wagyourtail.unimined'

def base = project ':api'

unimined.minecraft {
    version minecraft_1_16_5
    mappings {
        mojmap()
        devFallbackNamespace "official" // ensure the same fallback namespace
    }
    fabric {
        loader fabric_loader
    }
    defaultRemapJar = false
}

configurations {
    dev {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    dev jar
}

dependencies {
    api base
}

processResources {
    def replacements = [ 'adaptor': fabric_adaptor, 'injector': fabric_injector, 'version': version ]
    inputs.properties replacements
    from(base.processResources.outputs) {
        filesMatching('fabric.mod.json') {
            expand replacements
        }
    }
}

processTestResources {
    from base.processTestResources.outputs
}

jar {
    manifest {
        attributes([
                'Implementation-Title': mod_name,
                'Implementation-Version': mod_version
        ])
    }
    from(base.jar.archiveFile.collect { zipTree it })
    mustRunAfter ':api:build'
}

sourcesJar {
    mustRunAfter ':api:build'
}