/**
 * Common builds and sources relevant to all Fabric modules
 *
 * Base is 1.16.5
 */
plugins {
    alias libs.plugins.unimined
    alias libs.plugins.shadow
}

extendRunnable project, 8

uniminedCore project, 'fabric', false, []

setDev

def base = project ':api'

dependencies {
    api base
}

processResources {
    def replacements = [ 'adaptor': fabric_adaptor, 'injector': fabric_injector, 'version': version ]
    inputs.properties replacements
    from(base.processResources.outputs) {
        filesMatching('fabric.mod.json') {
            expand replacements
        }
    }
}

processTestResources {
    from base.processTestResources.outputs
}

jar {
    manifest {
        attributes([
                'Implementation-Title': mod_name,
                'Implementation-Version': mod_version
        ])
    }
    from(base.jar.archiveFile.collect { zipTree it })
    mustRunAfter ':api:build'
}

sourcesJar {
    mustRunAfter ':api:build'
}