//file:noinspection GroovyAssignabilityCheck

/**
 * 1.12.2 cleanroom build
 */

plugins {
    alias libs.plugins.shadow
    alias libs.plugins.unimined
}

extendFrom project, 'shadow'

uniminedCore project, 'cleanroom', true, [ dev_arg, common_entrypoint_arg, core_entrypoint_arg ]
remapJarDefaults project

dependencies {
    compileOnly legacy.bundles.cleanroom.compile
}

setSharedShadowJar ':api', ':legacy'