//file:noinspection DependencyNotationArgument

/**
 * 1.12.2 cleanroom build
 */
plugins {
    alias libs.plugins.shadow
    alias libs.plugins.unimined
}

extendRunnable()
extendFrom 'shadow'

uniminedCore 'cleanroom', true, [ dev_arg, common_entrypoint_arg, core_entrypoint_arg ]

setRepositories 'central', 'cf', 'ct', 'hei'

dependencies {
    api project(':api')
    api project(':legacy')

    annotationProcessor libs.bundles.legacy.annotations

    compileOnly legacy.bundles.cleanroom.compile
    compileOnly modsBundle('legacy', 'compile')

    implementation modsBundle('legacy', 'implementation')

    runtimeOnly modsBundle('legacy', 'runtime')
}

inheritCompileSources ':api', ':legacy'

inheritResources ':legacy'

addProjectJars ':legacy'

setJarsRunAfter true, ':legacy'

setSharedShadowJar()