import static org.gradle.api.logging.LogLevel.INFO
import static org.gradle.api.logging.LogLevel.QUIET

buildscript {
    repositories {
        gradlePluginPortal() {
            content {
                unimined_plugin_portal.split(';').each {grp ->
                    includeGroup grp
                }
            }
        }
        maven {
            name = 'WagYourMaven Releases'
            url = uri 'https://maven.wagyourtail.xyz/releases'
            content {
                unimined_releases.split(';').each {grp ->
                    includeGroup grp
                }
            }
        }
        maven {
            name = 'WagYourMaven Snapshots'
            url = uri 'https://maven.wagyourtail.xyz/snapshots'
            content {
                unimined_snapshots.split(';').each {grp ->
                    includeGroup grp
                }
            }
        }
    }
    dependencies {
        classpath "$shadow_plugin:$shadow_version"
        classpath "$unimined_plugin:$unimined_version"
    }
}

apply from: rootProject.file('gradle\\java23-module.gradle')

plugins.apply 'xyz.wagyourtail.unimined'

def base = project ':api'
def legacy = project ':legacy'

unimined.minecraft {
    version minecraft_1_12_2
    def args = [ dev_arg, common_entrypoint_arg, core_entrypoint_arg ]
    mappings {
        mcp 'stable', legacy_mappings_1_12_2
    }
    cleanroom {
        loader "0.3.0-alpha"
        runs.auth.username = minecraft_username
        runs.all {
            systemProperty 'foundation.verbose', 'true'
            jvmArgs args
            return
        }
    }
}

repositories {
    maven {
        name = 'CleanroomMC'
        url = uri 'https://maven.cleanroommc.com'
        content {
            [ 'com.cleanroommc', 'mezz' ].forEach {grp ->
                includeGroup grp
            }
        }
    }
    maven {
        name = 'CurseMaven'
        url = uri 'https://curse.cleanroommc.com/'
        content {
            includeGroup 'curse.maven'
        }
    }
    maven {
        name = 'BlameJared'
        url = uri 'https://maven.blamejared.com'
        content {
            [ 'bookshelf', 'gamestages' ].forEach {grp ->
                includeGroup "net.darkhax.$grp"
            }
        }
    }
}

dependencies {
    api base
    api legacy

    annotationProcessor "$gson_artifact:$gson_annotation"
    annotationProcessor "$guava_artifact:$guava_annotation"

    compileOnly "$cleanroom_mixin_artifact:$cleanroom_mixin_version"
    compileOnly "$dynamic_surroundings_artifact:$dynamic_surroundings_1_12_2"
    compileOnly "$lwjglx_artifact:$lwjglx_version"
    compileOnly "$orelib_artifact:$orelib_1_12_2"

    //mod support dependencies
    implementation "$bloodmoon_artifact:$bloodmoon_1_12_2"
    implementation "$bookshelf_artifact-$bookshelf_1_12_2"
    implementation "$champions_artifact:$champions_1_12_2"
    implementation "$coroutil_artifact:$coroutil_1_12_2"
    implementation "$game_stages_artifact-$game_stages_1_12_2"
    implementation "$infernal_mobs_artifact:$infernal_mobs_1_12_2"
    implementation "$nyx_artifact:$nyx_1_12_2"
    implementation "$serene_seasons_artifact:$serene_seasons_1_12_2"
    implementation "$weather2_remastered_artifact:$weather2_1_12_2"

    runtimeOnly "$hei_artifact:$hei_1_12_2"
}

compileJava {
    source base.sourceSets.main.allJava, legacy.sourceSets.main.allJava
}

compileTestJava {
    source base.sourceSets.test.allJava, legacy.sourceSets.test.allJava
}

processResources {
    from legacy.processResources.outputs
}

processTestResources {
    from legacy.processTestResources.outputs
}

jar {
    from(legacy.jar.archiveFile.collect { zipTree it })
    manifest {
        attributes([
                'FMLCorePlugin': legacy_entrypoint,
                'FMLCorePluginContainsFMLMod': true,
                'ForceLoadAsMod': true
        ])
    }
    finalizedBy shadowJar
    dependsOn ':legacy:build'
}

tasks.remapJar {
    doFirst {
        logging.captureStandardOutput INFO
    }
    doLast {
        logging.captureStandardOutput QUIET
    }
}

shadowJar {
    from(base.jar.archiveFile.collect { zipTree it })
}