import org.codehaus.groovy.runtime.MethodClosure

import static org.gradle.api.file.DuplicatesStrategy.EXCLUDE

/**
 * Setup shared Java plugin logic
 */
plugins {
    id 'idea'
    id 'java'
    id 'java-library'
}

group = base_package
version = mod_version


idea {
    module {
        downloadJavadoc = true
        downloadSources = true
    }
}

java {
    withSourcesJar()
    withJavadocJar()
}

tasks.withType(JavaCompile).configureEach {
    doFirst {
        options.encoding = 'UTF-8'
        options.deprecation = false
    }
}

tasks.withType(Jar).configureEach {
    duplicatesStrategy = EXCLUDE
    doFirst {
        archiveBaseName = mod_id
    }
}

tasks.withType(ProcessResources).configureEach {
    duplicatesStrategy = EXCLUDE
}

ext.addParentProcessedResources = this.&addParentProcessedResources as MethodClosure
ext.createConfiguration = this.&createConfiguration as MethodClosure
ext.createResourceArtifact = this.&createResourceArtifact as MethodClosure
ext.excludeResources = this.&excludeResources as MethodClosure
ext.setJarAndResourceDependencies = this.&setJarAndResourceDependencies as MethodClosure
ext.setJarAndResourceDependency = this.&setJarAndResourceDependency as MethodClosure
ext.setJarDependencies = this.&setJarDependencies as MethodClosure
ext.setJarDependency = this.&setJarDependency as MethodClosure
ext.setJavaVersion = this.&setJavaVersion as MethodClosure
ext.setResourceDependencies = this.&setResourceDependencies as MethodClosure
ext.setResourceDependency = this.&setResourceDependency as MethodClosure
ext.setResourceReplacements = this.&setResourceReplacements as MethodClosure

/**
 * Add the result of the processResources tasks from parent projects as dependencies.
 */
void addParentProcessedResources() {
    if('shared'!=name && isSharedProject()) {
        boolean minor_version = isMinorVersion()
        (isNeoforgeCompatible() ? [ 'Fabric', 'Forge', 'Neoforge' ] : [ 'Fabric', 'Forge' ]).forEach {loader ->
            String l_loader = loader.toLowerCase()
            String p_path = minor_version ? getFullPath(parent.name) : ":$l_loader"
            String t_name = "processTil${l_loader}Resources"
            String c_name = "parent${loader}Resources"
            createConfiguration "parent${loader}Resources", false, true
            addResourceConfigurations t_name, [ c_name ]
            addParentResourceDependency c_name, p_path, "processed${minor_version ? "$loader" : ''}Resources"
            tasks.named(t_name).configure {process_resources ->
                process_resources.mustRunAfter "$p_path:process${minor_version ? "Til$l_loader" : ''}Resources"
            }
        }
    } else {
        String p_path = isLegacyProject() ? ':legacy' : ':api'
        createConfiguration 'parentResources', false, true
        addResourceConfigurations 'processResources', [ 'parentResources' ]
        addParentResourceDependency 'parentResources', p_path, 'processedResources'
        tasks.processResources.mustRunAfter "$p_path:processResources"
    }
}

private void addParentResourceDependency(String c_name, String p_path, String p_config) {
    dependencies {
        "$c_name"(project(path: p_path, configuration: p_config))
    }
}

private void addResourceConfigurations(String t_name, List<String> config_names) {
    def loader = 'processResources'==t_name ? null : t_name.substring(7).replace('Resources', '').toLowerCase()
    def exclude_these = loader==null ? getDefaultExclusions() : getDefaultExclusionsForLoader(loader)
    def file_replacement = getDefaultFileReplacement()
    def replacements = getDefaultReplacements()
    tasks.named(t_name, Copy) {Copy process_resources ->
        final List<String> config_names_view = Collections.unmodifiableList config_names
        doFirst {
            config_names_view.forEach {config_name ->
                from(configurations.named(config_name)) {
                    process_resources.exclude exclude_these
                    if(file_replacement!=null) {
                        filesMatching(file_replacement) {
                            expand replacements
                        }
                    }
                }
            }
        }
    }
}

void createConfiguration(String config_name, boolean consumable, boolean resolvable) {
    configurations.create(config_name) {
        canBeConsumed = consumable
        canBeResolved = resolvable
    }
}

/**
 * Create an artifact for the processResources task that can be consumed as a dependency.
 */
void createResourceArtifact() {
    def config_map = [ processedResources: 'processResources' ]
    if('shared'!=name && isSharedProject()) {
        (isNeoforgeCompatible() ? [ 'Fabric', 'Forge', 'Neoforge' ] : [ 'Fabric', 'Forge' ]).forEach {loader ->
            String l_loader = loader.toLowerCase()
            config_map["processed${loader}Resources".toString()] = "processTil${l_loader}Resources".toString()
        }
    }
    config_map.forEach {config_name,task_name ->
        createConfiguration config_name, true, false
        artifacts.add(config_name, tasks.named(task_name, ProcessResources).map {process_resources ->
            process_resources.destinationDir
        })
    }
}

void excludeResources(String ... exclude_these) {
    if(exclude_these==null || exclude_these.length==0) return
    tasks.withType(ProcessResources).configureEach {
        final List<String> exclusion_view = List.of(exclude_these)
        doFirst {
            exclusion_view.forEach {String exclude_this->
                exclude exclude_this
            }
        }
    }
}

private List<String> getDefaultExclusions() {
    return switch(name) {
        case '1.12', 'cleanroom', 'legacy' -> [ "assets/$mod_id/lang/en_us.json", 'META-INF/coremods.json',
                                                'fabric.mod.json', 'multiversion_forge_core.js' ]
        case 'fabric' -> [ "assets/$mod_id/lang/en_us.lang", 'META-INF/coremods.json', 'mcmod.info',
                           'multiversion_forge_core.js' ]
        case 'forge', 'neoforge' -> [ "assets/$mod_id/lang/en_us.lang", 'fabric.mod.json', 'mcmod.info' ]
        case 'shared_1.16', 'shared_1.18', 'shared_1.19', 'shared_1.19.2', 'shared_1.19.4', 'shared_1.20',
                'shared_1.20.1', 'shared_1.20.4', 'shared_1.20.6', 'shared_1.21', 'shared_1.21.1' ->
            [ "assets/$mod_id/lang/en_us.lang", 'mcmod.info' ]
        default -> []
    }
}

private List<String> getDefaultExclusionsForLoader(String loader) {
    return switch(loader) {
        case 'legacy' ->
            [ "assets/$mod_id/lang/en_us.json", 'META-INF/coremods.json', 'fabric.mod.json', 'multiversion_forge_core.js' ]
        case 'fabric', 'tilfabric' ->
            [ "assets/$mod_id/lang/en_us.lang", 'META-INF/coremods.json', 'mcmod.info', 'multiversion_forge_core.js' ]
        case 'forge', 'neoforge', 'tilforge', 'tilneoforge' ->
            [ "assets/$mod_id/lang/en_us.lang", 'fabric.mod.json', 'mcmod.info' ]
        default -> []
    }
}

@SuppressWarnings('GrUnresolvedAccess')
private String getDefaultFileReplacement() {
    return switch(isLegacyProject() ? 'legacy' : name) {
        case 'fabric', 'tilfabric' -> 'fabric.mod.json'
        case 'legacy' -> 'mcmod.info'
        default -> null
    }
}

@SuppressWarnings(['GroovyAssignabilityCheck','GrUnresolvedAccess'])
private Map<String,?> getDefaultReplacements() {
    return switch(isLegacyProject() ? 'legacy' : name) {
        case 'fabric', 'tilfabric' -> [ 'adaptor': fabric_adaptor, 'injector': fabric_injector, 'version': version ]
        case 'legacy' -> [ 'minecraft_version': libs.versions.minecraft.'1'.'12'.'2'.get(), 'mod_author': mod_authors,
                           'mod_description': mod_description, 'mod_license': mod_license, 'mod_id': mod_id,
                           'mod_name': mod_name, 'mod_version': version ]
        default -> Collections.emptyMap()
    }
}

void setJarAndResourceDependencies(List<String> p_names, String ... exclude_these) {
    p_names.forEach {p_name ->
        setJarDependency p_name
        setResourceDependency p_name, exclude_these
    }
}

void setJarAndResourceDependency(String p_name, String ... exclude_these) {
    setJarDependency p_name
    setResourceDependency p_name, exclude_these
}

void setJarDependencies(List<String> p_names) {
    p_names.forEach {p_name ->
        setJarDependency p_name
    }
}

void setJarDependency(String p_name) {
    tasks.jar.dependsOn ":$p_name:jar"
    tasks.javadocJar.dependsOn ":$p_name:javadocJar"
    tasks.sourcesJar.dependsOn ":$p_name:sourcesJar"

}

void setJavaVersion(int java_version) {
    java {
        toolchain.languageVersion = JavaLanguageVersion.of java_version
    }
    if(java_version>=9) {
        tasks.withType(JavaCompile).configureEach {
            doFirst {
                options.release = java_version
            }
        }
    }
}

void setResourceDependencies(List<String> p_names, String ... exlude_these) {
    p_names.forEach {p_name ->
        setResourceDependency p_name, exlude_these
    }
}

void setResourceDependency(String p_name, String ... exclude_these) {
    tasks.withType(ProcessResources).configureEach {
        dependsOn ":$p_name:processResources"
    }
    excludeResources exclude_these
}

void setResourceReplacements(String replacement_file, Map<String,?> replacements) {
    processResources {
        final Map<String,?> replacements_view = Collections.unmodifiableMap replacements
        doFirst {
            filesMatching(replacement_file) {copy_details ->
                expand replacements_view
            }
        }
    }
}