import org.codehaus.groovy.runtime.MethodClosure

//noinspection GrUnresolvedAccess
initCommonDeps()

ext.modsBundle = this.&modsBundle as MethodClosure
ext.setCommonRepositories = this.&setCommonRepositories as MethodClosure

/**
 * Returns common maven data as a list from the given id
 * The list is formatted as name, uri, included groups
 */
private static List<String> commonMavenData(String id) {
    return switch(id) {
        case 'blamejared', 'bookshelf', 'crafttweaker', 'ct', 'darkhax','gamestages', 'jared', 'zen', 'zencode' ->
            [ 'BlameJared', 'maven.blamejared.com', 'com.blamejared.crafttweaker', 'net.darkhax.bookshelf',
              'net.darkhax.gamestages', 'org.openzen.zencode' ]
        case 'cf', 'curse', 'curseforge', 'cursemaven' -> [ 'CurseMaven', 'curse.cleanroommc.com/', 'curse.maven' ]
        case 'cleanroom', 'hei' -> [ 'CleanroomMC', 'maven.cleanroommc.com', 'mezz', 'zone.rong' ]
        case 'fast', 'fastutil', 'sonatype' ->
            [ 'SonaType', 'oss.sonatype.org/content/repositories/public/', 'it.unimi.dsi' ]
        case 'jei', 'modmaven' -> [ 'ModMaven', 'modmaven.dev', 'mezz.jei' ]
        case 'legacy', 'moddinglegacy' -> [ 'Modding Legacy', 'maven.moddinglegacy.com/maven', 'com.legacy' ]
        case 'modmenu', 'terraformers', 'terraformersmc' ->
            [ 'Terraformers', 'maven.terraformersmc.com/', 'com.terraformersmc' ]
        case 'modrinth' -> [ 'Modrinth', 'api.modrinth.com/maven', 'maven.modrinth' ]
        case 'nucleoid', 'pb4', 'placeholder' -> [ 'Nucleoid', 'maven.nucleoid.xyz/', 'eu.pb4']
        default -> []
    }
}

Provider<ExternalModuleDependencyBundle> modsBundle(String loader, String type) {
    if(isLegacyProject()) return project.legacy.bundles.mods.'1'.'12'.'2'."$type"
    String[] mc = projectMCVersion().split '_'
    return project."$loader".bundles.mods.'1'."${mc[1]}"."${mc[2]}"."$type"
}

void setCommonRepositories(List<String> maven_ids) {
    maven_ids.forEach {id ->
        if('central'==id) {
            repositories {
                mavenCentral()
            }
        } else setCommonRepositoryData commonMavenData(id)
    }
}

private void setCommonRepositoryData(List<String> maven_data) {
    if(maven_data==null || maven_data.empty) return
    final String maven_name = maven_data.get 0
    final String maven_location = maven_data.get 1
    final List<String> content_filter = maven_data.size()>2 ? maven_data.subList(2,maven_data.size()) : null
    repositories {
        maven {
            name = maven_name
            url = uri "https://$maven_location"
            if(content_filter!=null && !content_filter.empty) {
                content {
                    content_filter.forEach {grp ->
                        includeGroup grp
                    }
                }
            }
        }
    }
}