import static org.gradle.api.file.DuplicatesStrategy.EXCLUDE

plugins {
    id 'project-setup-common'
}

initJavaPlugin()
initDependencies()

configurations {
    modCompileOnly
    modRuntimeOnly
    compileOnly.extendsFrom modCompileOnly
    runtimeOnly.extendsFrom modRuntimeOnly
}

tasks.register('devRunJar',Jar) {
    archiveBaseName.set "$mod_id-dev_run"
    duplicatesStrategy = EXCLUDE
    from sourceSets.main.output
    from project(':api').sourceSets.main.output
    from project(':legacy').sourceSets.main.output
    manifest {
        Map<?,Object> entries = getManifestEntries()
        entries.put 'TILMultiversionCoreMods', core_entrypoint
        entries.put 'TILMultiversionMods', common_entrypoint
        attributes entries
    }
}

initUnimined()

unimined.minecraft {
    def legacy = project ':legacy'
    combineWith legacy, legacy.sourceSets.main
    if(isCleanroomProject()) {
        cleanroom {
            loader project.legacy.versions.cleanroom.loader.get()
        }
    } else {
        minecraftForge {
            loader legacyForgeVersion()
        }
    }
    runs.all {
        javaVersion = getJavaVersionEnum()
        classpath-=files(fixLegacyRuntimePaths())
        classpath+=files(devRunJar.archiveFile)
        Map<?,?> map = getSystemProperties()
        addCustomRunProperties map
        if(isCleanroomProject()) {
            map.put cleanroom_dump, 'true'
            map.put cleanroom_verbose, 'true'
        } else {
            map.put forge_log_markers_arg, forge_log_markers_values
            map.put forge_log_level, 'debug'
        }
    }
    mods {
        modImplementation {
            catchAWNamespaceAssertion()
        }
        remap(configurations.modCompileOnly) {
            catchAWNamespaceAssertion()
        }
        remap(configurations.modRuntimeOnly) {
            catchAWNamespaceAssertion()
        }
    }
}

remapForProduction isCleanroomProject() ? 'cleanroom' : 'forge'

setCommonRepositories(isCleanroomProject() ? [ 'central', 'cf', 'ct', 'hei' ] : [ 'cf', 'ct', 'hei' ])

dependencies {
    //noinspection DependencyNotationArgument,GrUnresolvedAccess
    annotationProcessor libs.bundles.legacy.annotations
    if(isCleanroomProject()) {
        //noinspection DependencyNotationArgument,GrUnresolvedAccess
        compileOnly legacy.bundles.cleanroom.compile
    }
    else modRuntimeOnly legacy.bundles.forge.runtime
    modCompileOnly modsBundle('legacy', 'compile')
    modImplementation modsBundle('legacy', 'implementation')
    modRuntimeOnly modsBundle('legacy', 'runtime')
    modRuntimeOnly legacy.bundles.nothirium
}

setJarAndResourceDependency 'legacy'
tasks.preRunClient.mustRunAfter 'devRunJar'

//noinspection GrUnresolvedAccess
applySourceHelpers()

List<String> fixLegacyRuntimePaths() {
    List<String> removed_paths = []
    if(!isLegacyProject()) return removed_paths
    [ project(':api'), project(':legacy'), project ].forEach {p ->
        logger.lifecycle "Removing '${p.name}' directory classpaths (dir=${p.projectDir.absolutePath})"
        [ 'classes\\java', 'resources' ].forEach {p_path ->
            String full_path = "${p.projectDir.absolutePath}\\build\\${p_path}\\main"
            removed_paths+=full_path
            logger.lifecycle "Removing '$full_path' from runtime classpath"
        }
    }
    return removed_paths
}