import static org.gradle.api.file.DuplicatesStrategy.EXCLUDE

plugins {
    id 'project-setup-common'
}

initJavaPlugin()
createResourceArtifact()
initDependencies()

createClassConfigs true, true

configurations {
    modCompileOnly
    modRuntimeOnly
    compileOnly.extendsFrom modCompileOnly
    runtimeOnly.extendsFrom modRuntimeOnly
}

//Enables using a jar for dev runs to bundle all the required subprojects into a single path
boolean use_dev_run_jar = true

if(use_dev_run_jar) {
    tasks.register('devRunJar',Jar) {
        [ 'classes', 'processResources' ].forEach {t_name ->
            it.mustRunAfter t_name
        }
        archiveBaseName.set "$mod_id-dev_run"
        duplicatesStrategy = EXCLUDE
        from sourceSets.main.output
        manifest {
            Map<?,Object> entries = getManifestEntries()
            entries.put 'TILMultiversionCoreMods', core_entrypoint
            entries.put 'TILMultiversionMods', common_entrypoint
            attributes entries
        }
    }
}


initUnimined()

unimined.minecraft {
    if(isCleanroomProject()) {
        cleanroom {
            loader project.legacy.versions.cleanroom.loader.get()
        }
    } else {
        minecraftForge {
            loader legacyForgeVersion()
        }
    }
    runs.all {
        javaVersion = getJavaVersionEnum()
        if(use_dev_run_jar) {
            classpath-=getBuildFiles([ 'classes\\java', 'resources' ], [ 'main' ])
            classpath+=files(devRunJar.archiveFile)
        }
        Map<?,?> map = getSystemProperties()
        addCustomRunProperties map, 'main'
        if(isCleanroomProject()) {
            map.put cleanroom_dump, 'true'
            map.put cleanroom_verbose, 'true'
        } else {
            map.put forge_log_markers_arg, forge_log_markers_values
            map.put forge_log_level, 'debug'
        }
    }
    mods {
        modImplementation {
            catchAWNamespaceAssertion()
        }
        remap(configurations.modCompileOnly) {
            catchAWNamespaceAssertion()
        }
        remap(configurations.modRuntimeOnly) {
            catchAWNamespaceAssertion()
        }
    }
}

remapForProduction isCleanroomProject() ? 'cleanroom' : 'forge'

setCommonRepositories(isCleanroomProject() ? [ 'central', 'cf', 'ct', 'hei' ] : [ 'cf', 'ct', 'hei' ])

dependencies {
    [ ':api', ':legacy' ].forEach {p_path ->
        compileOnly project(p_path)
        parentClasses project(path: p_path, configuration: 'exportClasses')
    }
    if(isCleanroomProject()) {
        //noinspection DependencyNotationArgument,GrUnresolvedAccess
        compileOnly legacy.bundles.cleanroom.compile
        parentClasses project(path: ':legacy:1.12', configuration: 'exportClasses')
    } else modRuntimeOnly legacy.bundles.forge.runtime
    //noinspection DependencyNotationArgument,GrUnresolvedAccess
    annotationProcessor libs.bundles.legacy.annotations
    modCompileOnly modsBundle('legacy', 'compile')
    modImplementation modsBundle('legacy', 'implementation')
    modRuntimeOnly modsBundle('legacy', 'runtime')
    modRuntimeOnly legacy.bundles.nothirium
}

addParentProcessedResources()

tasks.compileJava.mustRunAfter ':api:classes'
tasks.compileJava.mustRunAfter ':legacy:classes'
if(use_dev_run_jar) tasks.preRunClient.mustRunAfter 'devRunJar'

//noinspection GrUnresolvedAccess
applySourceHelpers()

List<String> fixLegacyRuntimePaths() {
//noinspection GrUnresolvedAccess
    return getBuildPaths([ 'classes\\java', 'resources' ], [ 'main' ])
}