plugins {
    id 'project-setup-common' //project-setup-common <- project-common-functions <- java-shared
}

initLoaderSetup()

@SuppressWarnings('GrUnresolvedAccess')
void initLoaderSetup() {
    initJavaPlugin()
    createResourceArtifact()
    registerClassesJar()
    plugins.apply 'common-deps'
    if(usesUnimined()) {
        initUnimined()
        finishUniminedSetup()
    }
    createClassConfigs false, true

    dependencies {
        compileOnly project(':api')
    }

    jar {
        manifest {
            attributes([
                    'Implementation-Title': mod_name,
                    'Implementation-Version': mod_version
            ])
        }
    }

    addParentProcessedResources()

    if('fabric'==name) setupFabricBase()

    tasks.compileJava.mustRunAfter ':api:classes'

    applySourceHelpers()
}

@SuppressWarnings('GrUnresolvedAccess')
private void finishUniminedSetup() {
    unimined.minecraft {
        remap(classesJar) {
            archiveBaseName = mod_id
            archiveClassifier = "$name-remapped"
            prodNamespace productionNamespace(name)
        }
        switch(name) {
            case 'fabric' -> {
                fabric {
                    loader fabricLoaderVersion()
                }
            }
            case 'forge' -> {
                minecraftForge {
                    loader modernForgeVersion()
                }
            }
            case 'neoforge' -> {
                neoForge {
                    loader neoforgeVersion()
                }
            }
        }
    }
}

/**
 * Register a jar task for bundling the compiled classes only
 */
@SuppressWarnings('GrUnresolvedAccess')
void registerClassesJar() {
    tasks.register('classesJar', Jar) {
        archiveBaseName = mod_id
        archiveClassifier = name
        dependsOn classes
        from sourceClassesDir('main')
    }
}

void setupFabricBase() {
    dependencies {
        //noinspection GrUnresolvedAccess
        modImplementation fabricApi.fabric(fabricAPIVersion())
    }
}