import org.codehaus.groovy.runtime.MethodClosure

import java.util.function.Function

import static org.gradle.api.file.DuplicatesStrategy.EXCLUDE

plugins {
    id 'project-setup-common'
}

initJavaPlugin()
initShadow()
initDependencies()
initConfigs()
createResourceArtifact()
createClassConfigs true, true
createLoaderClassConfigs()
initUnimined()

unimined.minecraft {
    //Nothing to do here
}

def official_mappings = mappingStyleOfficial()

unimined.minecraft(sourceSets.tilfabric) {
    combineWith sourceSets.main
    defaultRemapJar = true
    if(isRunnableVersion()) {
        runs{
            //noinspection ConfigurationAvoidance
            all {
                javaVersion = getJavaVersionEnum()
                Map<?,?> map = getSystemProperties()
                addCustomRunProperties map, 'tilfabric'
            }
            config('server') {
                args+=[ 'nogui' ]
            }
        }
    } else runs.off = true
    if(isRunnableVersion()) {
        mods {
            modImplementation {
                mixinRemap {
                    reset()
                    enableMixinExtra()
                    enableBaseMixin()
                    disableRefmap()
                }
            }
            remap(configurations.tilfabricModRuntimeOnly) {
                mixinRemap {
                    reset()
                    enableMixinExtra()
                    enableBaseMixin()
                    disableRefmap()
                }
            }
        }
    }
    //noinspection GroovyAssignabilityCheck
    fabric {
        loader project.fabric.versions.loader.get()
    }
}

remapTilfabricJar {
    archiveBaseName = mod_id
    archiveClassifier = 'fabric-remapped'
    prodNamespace 'intermediary'
}

// Only fabric is relocated since forge and neoforge technically both use the same intermediary
// production namespace in 1.20.1 before neoforge switched to using official mappings
shadowJar {
    archiveBaseName = mod_id
    archiveClassifier = 'fabric-remapped-relocated'
    //noinspection GroovyAssignabilityCheck
    configurations = [ project.configurations.shadow ]
    dependsOn 'remapTilfabricJar'
    //noinspection GroovyAssignabilityCheck
    relocate "${base_package}.shared", "${base_package}.fabric"
}

//noinspection GrUnresolvedAccess,GroovyAssignabilityCheck
tasks.assemble.dependsOn shadowJar

unimined.minecraft(sourceSets.tilforge) {
    combineWith sourceSets.main
    if(!mappingStyleOfficial()) defaultRemapJar = true
    if(isRunnableVersion()) {
        if(!isJava8()) {
            def build_files = getBuildFiles([main: [ 'classes\\java' ], tilforge: [ 'classes\\java', 'resources' ]])
            logger.lifecycle "Adding build files to forge minecraftLibraries $build_files"
            configurations.tilforgeMinecraftLibraries.dependencies.add dependencies.create(build_files)
            tasks.compileTilforgeJava.mustRunAfter 'processTilforgeResources'
        }
        runs {
            //noinspection ConfigurationAvoidance
            all {
                javaVersion = getJavaVersionEnum()
                Map<?,?> map = getSystemProperties()
                addCustomRunProperties map, 'tilforge'
                //noinspection GroovyAssignabilityCheck
                map[debug_network] = 'true'
                //noinspection GroovyAssignabilityCheck
                map[forge_log_level] = 'debug'
                //noinspection GroovyAssignabilityCheck
                map[forge_log_markers_arg] = forge_log_markers_values
                //noinspection GroovyAssignabilityCheck
                map[forge_module_layer_movement] = 'false'
            }
            config('client') {
                args+=[ '--username', minecraft_username, '--uuid', minecraft_uuid ]
            }
            config('server') {
                args+=[ 'nogui' ]
            }
        }
    } else runs.off = true
    if(isRunnableVersion()) {
        mods {
            modImplementation {
                mixinRemap {
                    reset()
                    enableMixinExtra()
                    enableBaseMixin()
                }
            }
            remap(configurations.tilforgeModRuntimeOnly) {
                catchAWNamespaceAssertion()
                mixinRemap {
                    reset()
                    enableMixinExtra()
                    enableBaseMixin()
                }
            }
        }
    }
    minecraftForge {
        loader modernForgeVersion()
    }
}
if(!official_mappings) {
    remapTilforgeJar {
        archiveBaseName = mod_id
        archiveClassifier = 'forge-remapped'
        prodNamespace 'searge'
    }
}

if(isNeoforgeCompatible()) {
    unimined.minecraft(sourceSets.tilneoforge) {
        combineWith sourceSets.main
        if(!mappingStyleOfficial()) defaultRemapJar = true
        if(isRunnableVersion()) {
            //def build_files = getBuildFiles([main: [ 'classes\\java' ], tilneoforge: [ 'classes\\java', 'resources' ]])
            //logger.lifecycle "Adding build files to neoforge minecraftLibraries $build_files"
            //configurations.tilneoforgeMinecraftLibraries.dependencies.add dependencies.create(build_files)
            //tasks.compileTilneoforgeJava.mustRunAfter 'processTilneoforgeResources'
            runs{
                //noinspection ConfigurationAvoidance
                all {
                    javaVersion = getJavaVersionEnum()
                    Map<?,?> map = getSystemProperties()
                    addCustomRunProperties map, 'tilneoforge'
                    //noinspection GroovyAssignabilityCheck
                    map[debug_network] = 'true'
                    //noinspection GroovyAssignabilityCheck
                    map[forge_log_level] = 'debug'
                    //noinspection GroovyAssignabilityCheck
                    map[forge_log_markers_arg] = forge_log_markers_values
                    //noinspection GroovyAssignabilityCheck
                    map[neoforge_module_layer_movement] = 'false'
                }
                config('server') {
                    args+=[ 'nogui' ]
                }
            }
        } else runs.off = true
        if(isRunnableVersion()) {
            mods {
                modImplementation {
                    mixinRemap {
                        reset()
                        enableMixinExtra()
                        enableBaseMixin()
                        disableRefmap()
                    }
                }
                remap(configurations.tilneoforgeModRuntimeOnly) {
                    mixinRemap {
                        reset()
                        enableMixinExtra()
                        enableBaseMixin()
                        disableRefmap()
                    }
                }
            }
        }
        neoForge {
            loader neoforgeVersion()
        }
    }
    if(!official_mappings) {
        remapTilneoforgeJar {
            archiveBaseName = mod_id
            archiveClassifier = 'neoforge-remapped'
            prodNamespace 'searge'
        }
    }
}

ext.setupShared = this.&setupShared as MethodClosure

List<String> collectRunAfter() {
    def run_after = [ ':shared' ]
    //noinspection GrUnresolvedAccess
    if(isMinorVersion()) {
        run_after+=":${parent.name}"
        switch(name) {
            case '1.19.4': {
                run_after+=":shared_1.19.2"
                break
            }
            case '1.20.4': {
                run_after+=":shared_1.20.1"
                break
            }
            case '1.20.6': {
                run_after+=":shared_1.20.4"
                break
            }
        }
    }
    return run_after as List<String>
}

void createJarTasks() {
    //noinspection GrUnresolvedAccess
    def loaders = isNeoforgeCompatible() ? [ 'fabric', 'forge', 'neoforge' ] : [ 'fabric', 'forge' ]
    loaders.forEach {loader ->
        String task_name = "til${loader}Jar"
        tasks.register(task_name, Jar) {jar_task ->
            archiveBaseName = mod_id
            archiveClassifier = loader
            duplicatesStrategy = EXCLUDE
            from sourceSets."til$loader".output
        }
        tasks.assemble.dependsOn task_name
    }
}

void initConfigs() {
    setLoaderConfigs()
    //noinspection GrUnresolvedAccess
    if(isRunnableVersion()) {
        //noinspection GrUnresolvedAccess
        def loaders = isNeoforgeCompatible() ? [ 'fabric', 'forge', 'neoforge' ] : [ 'fabric', 'forge' ]
        configurations {
            loaders.forEach {loader ->
                //noinspection GrUnresolvedAccess
                logger.lifecycle "Adding runnable $loader configs"
                [ 'CompileOnly', 'Implementation', 'RuntimeOnly' ].forEach {config_name ->
                    named("til$loader$config_name").get().extendsFrom create("til${loader}Mod$config_name")
                }
            }
            if(!isJava8()) { //Add shaded dependencies to the legacy_classpath for dev runs
                forgeLegacyClasspathImplementation
                tilforgeImplementation.extendsFrom forgeLegacyClasspathImplementation
                tilforgeMinecraftLibraries.extendsFrom forgeLegacyClasspathImplementation
                if(isNeoforgeCompatible()) {
                    neoforgeLegacyClasspathImplementation
                    tilneoforgeImplementation.extendsFrom neoforgeLegacyClasspathImplementation
                    tilneoforgeMinecraftLibraries.extendsFrom neoforgeLegacyClasspathImplementation
                }
            }
        }
    }
}

void setLoaderConfigs() {
    sourceSets {
        //noinspection GrUnresolvedAccess
        def main_output = sourceSets.main.output
        tilfabric {
            compileClasspath+=main_output
            runtimeClasspath+=main_output
        }
        tilforge {
            compileClasspath+=main_output
            runtimeClasspath+=main_output
        }
        if(isNeoforgeCompatible) {
            tilneoforge {
                compileClasspath+=main_output
                runtimeClasspath+=main_output
            }
        }
    }
    createJarTasks()
    configurations {
        tilfabric {
            canBeResolved = false
            canBeConsumed = true
        }
        tilforge {
            canBeResolved = false
            canBeConsumed = true
        }
        if(neoforge_compatible) {
            tilneoforge {
                canBeResolved = false
                canBeConsumed = true
            }
        }
    }
    artifacts {
        //noinspection GrUnresolvedAccess
        tilfabric tilfabricJar
        //noinspection GrUnresolvedAccess
        tilforge tilforgeJar
        //noinspection GrUnresolvedAccess
        if(isNeoforgeCompatible()) {
            //noinspection GrUnresolvedAccess
            tilneoforge tilneoforgeJar
        }
    }
}

@SuppressWarnings('GrUnresolvedAccess')
void setupShared(List<String> extra_maven_ids) {
    setSharedDependencies extra_maven_ids
    addParentProcessedResources()
    setJarsRunAfter collectRunAfter()
    applySourceHelpers()
}

void setSharedDependencies(List<String> extra_maven_ids) {
    List<String> maven_ids = []
    //noinspection GrUnresolvedAccess
    if(isRunnableVersion()) {
        maven_ids = [ 'cf', 'ct', 'jei', 'modrinth', 'modmenu' ]
        maven_ids.addAll extra_maven_ids
    }
    setSharedDependenciesInner maven_ids
}

@SuppressWarnings('GrUnresolvedAccess')
void setSharedDependenciesInner(List<String> maven_ids) {
    if(isLoaderBase()) return

    //Makes it so runtime mods can be disabled per loader to avoid mapping issues when testing
    List<String> enabled_runtime_mods = [ ]
    //Selectively enable which versions should have Music Triggers added to the runtime
    Map<String,List<String>> enabled_mt = [fabric: [ 'all' ], forge: [ 'all' ], neoforge: [ 'all' ]]
    boolean neoforge_legacy_classpath = true
    Function<String,Boolean> check_legacy_classpath = l -> 'forge'==l || (neoforge_legacy_classpath && 'neoforge'==l)

    setCommonRepositories maven_ids
    def loaders = isNeoforgeCompatible() ? [ 'Fabric', 'Forge', 'Neoforge' ] : [ 'Fabric', 'Forge' ]
    boolean minor_version = isMinorVersion()
    boolean runnable_version = isRunnableVersion()
    dependencies {
        compileOnly project(':api')
        if(runnable_version) {
            parentClasses project(path: ':api', configuration: 'exportClasses')
            if(!isJava8()) {
                forgeLegacyClasspathImplementation libs.bundles.burningwave
                if(neoforge_legacy_classpath) neoforgeLegacyClasspathImplementation libs.bundles.burningwave
            }
        }
        if(minor_version) {
            compileOnly parent
            parentClasses project(path: parent.path, configuration: 'exportClasses')
        }
        tilfabricModImplementation fabricApi.fabric(fabricAPIVersion())
        loaders.forEach {loader ->
            String l_loader = loader.toLowerCase()
            "til${l_loader}AnnotationProcessor" libs.lombok
            "til${l_loader}CompileOnly" project(':api')
            "til${l_loader}CompileOnly" project(":$l_loader")
            "til${l_loader}CompileOnly" libs.lombok
            if(minor_version) {
                "parent${loader}Classes"(project(path: parent.path, configuration: "export${loader}Classes"))
                "til${l_loader}CompileOnly" parent
                "til${l_loader}CompileOnly" project(path: parent.path, configuration: "til$l_loader")
            }
            if(runnable_version) {
                "parent${loader}Classes"(project(path: ":$l_loader", configuration: 'exportClasses'))
                "til${l_loader}ModCompileOnly"(modsBundle(l_loader, 'compile')) {
                    exclude group: 'net.fabricmc'
                }
                "til${l_loader}ModImplementation"(modsBundle(l_loader, 'implementation')) {
                    exclude group: 'net.fabricmc'
                }
                if(enabled_runtime_mods.contains(l_loader)) {
                    "til${l_loader}ModRuntimeOnly"(modsBundle(l_loader, 'runtime')) {
                        exclude group: 'net.fabricmc'
                    }
                }
                def mt_versions = enabled_mt[l_loader]
                if(mt_versions!=null && (mt_versions.contains('all') || mt_versions.contains(minecraftVersion())))
                    "til${l_loader}RuntimeOnly"(libs.musictriggers)
                if(isJava8() || !check_legacy_classpath.apply(l_loader))
                    "til${l_loader}Implementation" libs.bundles.burningwave
            } else if(isJava8() || !check_legacy_classpath.apply(l_loader))
                "til${l_loader}Implementation" libs.bundles.burningwave
        }
    }
    tasks.compileJava.mustRunAfter "${parent.path}:classes"
    loaders.forEach {loader ->
        String l_loader = loader.toLowerCase()
        tasks.named("til${l_loader}Classes").configure {
            mustRunAfter 'classes'
        }
        if(minor_version) {
            String p_task = "${parent.path}:inheritParent${loader}Classes"
            tasks.named("compileTil${l_loader}Java").configure {
                mustRunAfter p_task
            }
            tasks.compileJava.mustRunAfter p_task
            tasks.named("inheritParent${loader}Classes").configure {
                mustRunAfter ":${parent.path}:classes"
                mustRunAfter "${parent.path}:til${l_loader}Classes"
                mustRunAfter ":${l_loader}:classes"
                mustRunAfter ":api:classes"
            }
        } else {
            tasks.named("inheritParent${loader}Classes").configure {
                mustRunAfter ":${l_loader}:classes"
                mustRunAfter ":api:classes"
            }
        }
    }
}