import org.codehaus.groovy.runtime.MethodClosure

/**
 * Initialize common functions
 */
plugins {
    id 'project-common-functions'
}

ext.applySourceHelpers = this.&applySourceHelpers as MethodClosure
ext.initDependencies = this.&initDependencies as MethodClosure
ext.initJavaPlugin = this.&initJavaPlugin as MethodClosure
ext.initShadow = this.&initShadow as MethodClosure
ext.initUnimined = this.&initUnimined as MethodClosure

void applySourceHelpers() {
    logger.lifecycle 'applySourceHelpers'
    plugins.apply 'source-helpers'
    logger.lifecycle 'Finished applying source-helpers plugin'
    //noinspection GrUnresolvedAccess
    setupSourceGenGraph()
}

/**
 * Initialize the project-dependencies plugin
 */
void initDependencies() {
    plugins.apply 'project-dependencies'
}

/**
 * Initialize the project-status plugin
 * Use project-status to set the correct Java toolchain version
 */
void initJavaPlugin() {
    initProjectStatus()
    //noinspection GrUnresolvedAccess
    setJavaVersion getJavaVersion()
}

void initShadow() {
    plugins.apply 'com.gradleup.shadow'
}

void initProjectStatus() {
    plugins.apply 'project-status'
    if(experimental_setup) plugins.apply 'project-experimental'
}

void initUnimined() {
    plugins.apply 'unimined-common'
}