import org.codehaus.groovy.runtime.MethodClosure

import static org.gradle.api.file.DuplicatesStrategy.EXCLUDE

plugins {
    id 'project-setup-common'
}

initJavaPlugin()
initDependencies()
initConfigs()
initUnimined()

unimined.minecraft {
    def shared = project ':shared'
    combineWith shared, shared.sourceSets.main
}

def official_mappings = mappingStyleOfficial()

unimined.minecraft(sourceSets.fabric) {
    combineWith sourceSets.main
    defaultRemapJar = true
    //noinspection GroovyAssignabilityCheck
    fabric {
        loader project.fabric.versions.loader.get()
    }
    if(isRunnableVersion()) {
        runs.all {
            javaVersion = getJavaVersionEnum()
            Map<?,?> map = getSystemProperties()
            addCustomRunProperties(map)
        }
    } else runs.off = true
    mods {
        if(isRunnableVersion()) {
            remap(configurations.fabricModRuntimeOnly) {
                catchAWNamespaceAssertion()
                namespace 'mojmap'
            }
        }
    }
}

remapFabricJar {
    archiveBaseName = mod_id
    archiveClassifier = 'fabric-remapped'
    prodNamespace 'intermediary'
}

// Only fabric is relocated since forge and neoforge technically both use the same intermediary
// production namespace in 1.20.1 before neoforge switched to using official mappings
shadowJar {
    archiveBaseName = mod_id
    archiveClassifier = 'fabric-remapped-relocated'
    //noinspection GroovyAssignabilityCheck
    configurations = [ project.configurations.shadow ]
    dependsOn 'remapFabricJar'
    //noinspection GroovyAssignabilityCheck
    relocate "${base_package}.shared", "${base_package}.fabric"
}
tasks.assemble.dependsOn shadowJar

unimined.minecraft(sourceSets.forge) {
    combineWith sourceSets.main
    if(!mappingStyleOfficial()) defaultRemapJar = true
    minecraftForge {
        loader modernForgeVersion()
    }
    if(isRunnableVersion()) {
        runs.all {
            javaVersion = getJavaVersionEnum()
            Map<?,?> map = getSystemProperties()
            addCustomRunProperties(map)
        }
    } else runs.off = true
    mods {
        if(isRunnableVersion()) {
            remap(configurations.forgeModRuntimeOnly) {
                catchAWNamespaceAssertion()
                namespace 'mojmap'
            }
        }
    }
}
if(!official_mappings) {
    remapForgeJar {
        archiveBaseName = mod_id
        archiveClassifier = 'forge-remapped'
        prodNamespace 'searge'
    }
}

if(isNeoforgeCompatible()) {
    unimined.minecraft(sourceSets.neoforge) {
        combineWith sourceSets.main
        if(!mappingStyleOfficial()) defaultRemapJar = true
        neoForge {
            loader neoforgeVersion()
        }
        if(isRunnableVersion()) {
            runs.all {
                javaVersion = getJavaVersionEnum()
                Map<?,?> map = getSystemProperties()
                addCustomRunProperties(map)
            }
        } else runs.off = true
        mods {
            if(isRunnableVersion()) {
                remap(configurations.neoforgeModRuntimeOnly) {
                    catchAWNamespaceAssertion()
                    namespace 'mojmap'
                }
            }
        }
    }
    if(!official_mappings) {
        remapNeoforgeJar {
            archiveBaseName = mod_id
            archiveClassifier = 'neoforge-remapped'
            prodNamespace 'searge'
        }
    }
}

ext.setupShared = this.&setupShared as MethodClosure

List<String> collectRunAfter() {
    def run_after = [ ':shared' ]
    //noinspection GrUnresolvedAccess
    if(isMinorVersion()) {
        run_after+=":${parent.name}"
        switch(name) {
            case '1.19.4': {
                run_after+=":shared_1.19.2"
                break
            }
            case '1.20.4': {
                run_after+=":shared_1.20.1"
                break
            }
            case '1.20.6': {
                run_after+=":shared_1.20.4"
                break
            }
        }
    }
    return run_after as List<String>
}

void createJarTasks() {
    def loaders = isNeoforgeCompatible() ? [ 'fabric', 'forge', 'neoforge' ] : [ 'fabric', 'forge' ]
    loaders.forEach {loader ->
        String task_name = "${loader}Jar"
        tasks.register(task_name, Jar) {jar_task ->
            jar_task.archiveBaseName = mod_id
            jar_task.archiveClassifier = loader
            jar_task.duplicatesStrategy = EXCLUDE
            jar_task.from sourceSets."$loader".output
        }
        tasks.assemble.dependsOn task_name
    }
}

void initConfigs() {
    setLoaderConfigs()
    if(isRunnableVersion()) {
        configurations {
            fabricModCompileOnly
            forgeModCompileOnly
            fabricModImplementation
            forgeModImplementation
            fabricModRuntimeOnly
            forgeModRuntimeOnly
            fabricCompileOnly.extendsFrom fabricModCompileOnly
            forgeCompileOnly.extendsFrom forgeModCompileOnly
            fabricImplementation.extendsFrom fabricModImplementation
            forgeImplementation.extendsFrom forgeModImplementation
            fabricRuntimeOnly.extendsFrom fabricModRuntimeOnly
            forgeRuntimeOnly.extendsFrom forgeModRuntimeOnly
            if(isNeoforgeCompatible) {
                neoforgeModCompileOnly
                neoforgeModImplementation
                neoforgeModRuntimeOnly
                neoforgeCompileOnly.extendsFrom neoforgeModCompileOnly
                neoforgeImplementation.extendsFrom neoforgeModImplementation
                neoforgeRuntimeOnly.extendsFrom neoforgeModRuntimeOnly
            }
        }
    } else setDev()
}

void setLoaderConfigs() {
    sourceSets {
        def main_output = sourceSets.main.output
        fabric {
            compileClasspath+=main_output
            runtimeClasspath+=main_output
        }
        forge {
            compileClasspath+=main_output
            runtimeClasspath+=main_output
        }
        if(isNeoforgeCompatible) {
            neoforge {
                compileClasspath+=main_output
                runtimeClasspath+=main_output
            }
        }
    }
    createJarTasks()
    configurations {
        fabric {
            canBeResolved = false
            canBeConsumed = true
        }
        forge {
            canBeResolved = false
            canBeConsumed = true
        }
        if(neoforge_compatible) {
            neoforge {
                canBeResolved = false
                canBeConsumed = true
            }
        }
    }
    artifacts {
        //noinspection GroovyAssignabilityCheck
        fabric fabricJar
        //noinspection GroovyAssignabilityCheck
        forge forgeJar
        if(isNeoforgeCompatible()) {
            //noinspection GroovyAssignabilityCheck
            neoforge neoforgeJar
        }
    }
}

void setupShared(List<String> extra_maven_ids) {
    setSharedDependencies extra_maven_ids
    inheritResources([ ':shared' ], 'mcmod.info')
    setJarsRunAfter collectRunAfter()
}

void setSharedDependencies(List<String> extra_maven_ids) {
    List<String> maven_ids = []
    if(isRunnableProject()) {
        maven_ids = [ 'cf', 'ct', 'jei', 'modrinth', 'modmenu' ]
        maven_ids.addAll extra_maven_ids
    }
    setSharedDependenciesInner maven_ids
}

void setSharedDependenciesInner(List<String> maven_ids) {
    if(isLoaderBase) return
    setRepositories maven_ids
    dependencies {
        if(isMinorVersion) compileOnlyApi parent
        fabricModImplementation fabricApi.fabric(fabricAPIVersion())
        def types = isNeoforgeCompatible() ? [ 'fabric', 'forge', 'neoforge' ] : [ 'fabric', 'forge' ]
        types.forEach {loader ->
            logger.lifecycle "Applying $loader-specific dependencies for $name"
            "${loader}CompileOnly" project(path: ":$loader", configuration: 'dev')
            "${loader}Implementation" libs.bundles.burningwave
            "${loader}AnnotationProcessor" libs.lombok
            "${loader}CompileOnly" libs.lombok
            if(isRunnableProject) {
                if(isMinorVersion) {
                    "${loader}Implementation" parent
                    "${loader}Implementation" project(path: parent.path, configuration: "$loader")
                }
                "${loader}ModImplementation" modsBundle(loader, 'implementation')
                "${loader}ModRuntimeOnly" modsBundle(loader, 'runtime')
            }
        }
    }
}