plugins {
    id 'project-setup-common'
}

//noinspection GrUnresolvedAccess
initJavaPlugin()
plugins.apply 'common-deps'

//noinspection GrUnresolvedAccess
if(usesUnimined) {
//noinspection GrUnresolvedAccess
    initUnimined()
    finishUniminedSetup()
    if('fabric'==name) {
        dependencies {
            //noinspection GrUnresolvedAccess
            fabricApi.fabric(fabricAPIVersion())
        }
    }
}

//noinspection GrUnresolvedAccess
setDev()

dependencies {
    api project(':api')
}

jar {
    manifest {
        attributes([
                'Implementation-Title': mod_name,
                'Implementation-Version': mod_version
        ])
    }
}

//noinspection GrUnresolvedAccess
setJarAndResourceDependency 'api'

if('fabric'==name) setupFabricBase()
else {
    processResources {
        exclude 'fabric.mod.json'
    }
}

//noinspection GrUnresolvedAccess
applySourceHelpers()

@SuppressWarnings('GrUnresolvedAccess')
private void finishUniminedSetup() {
    unimined.minecraft {
        switch(name) {
            case 'fabric' -> {
                fabric {
                    loader fabricLoaderVersion()
                }
            }
            case 'forge' -> {
                minecraftForge {
                    loader modernForgeVersion()
                }
            }
            case 'neoforge' -> {
                neoForge {
                    loader neoforgeVersion()
                }
            }
        }
    }
    remapForProduction(name)
}

void setupFabricBase() {
    def replacements = [ 'adaptor': fabric_adaptor, 'injector': fabric_injector, 'version': version ]
    //noinspection GrUnresolvedAccess
    setResourceReplacements 'fabric.mod.json', replacements
}