plugins {
    id 'project-setup-common'
}

//noinspection GrUnresolvedAccess
initJavaPlugin()
createResourceArtifact()
plugins.apply 'common-deps'

//noinspection GrUnresolvedAccess
if(usesUnimined) {
//noinspection GrUnresolvedAccess
    initUnimined()
    finishUniminedSetup()
}

createClassConfigs false, true

dependencies {
    compileOnly project(':api')
}

jar {
    manifest {
        attributes([
                'Implementation-Title': mod_name,
                'Implementation-Version': mod_version
        ])
    }
}

addParentProcessedResources()

if('fabric'==name) setupFabricBase()

tasks.compileJava.mustRunAfter ':api:classes'

//noinspection GrUnresolvedAccess
applySourceHelpers()

/**
 * Register a jar task for bundling the compiled classes only
 */
tasks.register('classesJar', Jar) {
    archiveBaseName = mod_id
    archiveClassifier = name
    dependsOn classes
    from(sourceClassesDir('main'))
}

@SuppressWarnings('GrUnresolvedAccess')
private void finishUniminedSetup() {
    unimined.minecraft {
        switch(name) {
            case 'fabric' -> {
                fabric {
                    loader fabricLoaderVersion()
                }
            }
            case 'forge' -> {
                minecraftForge {
                    loader modernForgeVersion()
                }
            }
            case 'neoforge' -> {
                neoForge {
                    loader neoforgeVersion()
                }
            }
        }
        remap(classesJar) {
            archiveBaseName = mod_id
            archiveClassifier = "$name-remapped"
            prodNamespace productionNamespace(name)
        }
    }
}

void setupFabricBase() {
    dependencies {
        //noinspection GrUnresolvedAccess
        modImplementation fabricApi.fabric(fabricAPIVersion())
    }
}