import org.codehaus.groovy.runtime.MethodClosure

import java.util.function.Function

plugins {
    id 'project-setup-common' //project-setup-common <- project-common-functions <- java-shared
}

initShared()

//Bundled into a method just for easy warning supression
@SuppressWarnings('GrUnresolvedAccess')
void initShared() {
    initJavaPlugin()                //project-setup-common
    initShadow()                    //project-setup-common
    initDependencies()              //project-setup-common
    setLoaderConfigs()
    createResourceArtifact()        //java-shared
    createClassConfigs true, true   //project-common-functions
    createLoaderClassConfigs()      //project-common-functions
    initUnimined()                  //unimined-common
    finalizeUnimined()
}

/**
 * Forge/Neoforge logging markers are calculated during SERVICE layer initializtion but we can just do it manually
 */
void addForgeLoggingMarkers(Map<?,?> propertyMap, boolean reduced, String ... exclusions) {
    List<String> exclude_these = List.of exclusions
    (reduced ? forge_log_markers_reduced : forge_log_markers_all).split(',').each {marker ->
        if(!exclude_these.contains(marker)) {
            //noinspection GroovyAssignabilityCheck
            propertyMap["${forge_log_marker_arg}.$marker".toString()] = 'ACCEPT'
        }
    }
}

List<String> collectRunAfter() {
    return switch(name) {
        case 'shared_1.16', 'shared_1.18', 'shared_1.19', 'shared_1.20', 'shared_1.21' -> [ parent.name ]
        case 'shared_1.19.2', 'shared_1.20.1', 'shared_1.21.1' -> [ parent.parent.name, parent.name ]
        case 'shared_1.19.4' -> [ parent.parent.name, parent.name, "${parent.name}.2" ]
        case 'shared_1.20.4' -> [ parent.parent.name, parent.name, "${parent.name}.1" ]
        case 'shared_1.20.6' -> [ parent.parent.name, parent.name, "${parent.name}.4" ]
        default -> []
    }
}

@SuppressWarnings('GrUnresolvedAccess')
void finalizeUnimined() {
    unimined.minecraft {
        //Nothing to do here
    }
    (getLoaderList(false)).forEach {String loader ->
        uniminedSetupLoader sourceSets.named("til$loader").get(), loader
        if(isRunnableVersion() && !isJava8() && [ 'forge', 'neoforge' ].contains(loader)) setupForgeLikeConfigs loader
    }
}

/**
 * Only fabric is relocated since forge and neoforge technically both use the same intermediary production namespace in
 * 1.20.1 before neoforge switched to using official mappings
 */
@SuppressWarnings('GrUnresolvedAccess')
void initFabricShading() {
    shadowJar {
        archiveBaseName = mod_id
        archiveClassifier = 'fabric-relocated'
        configurations = [ project.configurations.shadow ]
        dependsOn 'fabricClassesJar'
        relocate "${base_package}.shared", "${base_package}.fabric"
    }
}

@SuppressWarnings('GrUnresolvedAccess')
TaskProvider<Jar> registerClassesJar(String loader) {
    return tasks.register(loader==null ? 'classesJar' : "${loader}ClassesJar", Jar) {
        archiveBaseName = mod_id
        archiveClassifier = loader==null ? 'main' : loader
        dependsOn loader==null ? 'classes' : "til${loader}Classes"
        File main_classes = sourceClassesDir('main')
        if(loader==null) from(main_classes)
        else {
            from(sourceClassesDir("til$loader"))
            from(main_classes) {
                //Avoid needing to exclude duplicate api classes in every subproject by handling them in the main build
                exclude '**/api/**'
                //Forge & Neoforge use the same intermediary mappings so we don't have to remap shared stuff in both
                if('neoforge'==loader) '**/shared/**'
            }
        }
    } as TaskProvider<Jar>
}

void setForgeLoggingLevel(Map<?,?> propertyMap, String level, String ... exclusions) {
    List<String> exclude_these = List.of exclusions
    forge_log_level_all.split(',').each {log ->
        if(!exclude_these.contains(log)) {
            //noinspection GroovyAssignabilityCheck
            propertyMap["forge.logging.${log}.level".toString()] = level
        }
    }
}

@SuppressWarnings('GrUnresolvedAccess')
void setLoaderConfigs() {
    getLoaderList(false).forEach {String loader ->
        String source_name = "til$loader"
        sourceSets.create(source_name) {
            compileClasspath+=sourceSets.main.output
            runtimeClasspath+=sourceSets.main.output
        }
        def jar_provider = registerClassesJar loader
        configurations.create(source_name) {
            canBeResolved = false
            canBeConsumed = true
        }
        artifacts.add source_name, jar_provider
        if('fabric'==loader) initFabricShading()
        if(isRunnableVersion()) {
            logger.lifecycle "Adding runnable $loader configs"
            [ 'CompileOnly', 'Implementation', 'RuntimeOnly' ].forEach {config_name ->
                configurations {
                    named("$source_name$config_name").get().extendsFrom create("${source_name}Mod$config_name")
                }
            }
        }
    }
}

void setSharedDependencies(List<String> extra_maven_ids) {
    List<String> maven_ids = []
    //noinspection GrUnresolvedAccess
    if(isRunnableVersion()) {
        maven_ids = [ 'cf', 'ct', 'jei', 'modrinth', 'modmenu' ]
        maven_ids.addAll extra_maven_ids
    }
    setSharedDependenciesInner maven_ids
}

@SuppressWarnings('GrUnresolvedAccess')
void setSharedDependenciesInner(List<String> maven_ids) {
    if(isLoaderBase()) return

    //Makes it so runtime mods can be disabled per loader to avoid mapping issues when testing
    List<String> enabled_runtime_mods = [ ]
    //Selectively enable which versions should have Music Triggers added to the runtime
    Map<String,List<String>> enabled_mt = [ fabric: [ 'all' ], forge: [ 'all' ], neoforge: [ 'all' ] ]
    boolean enable_neoforge_legacy_classpath = true
    boolean neoforge_legacy_classpath = isNeoforgeCompatible() && enable_neoforge_legacy_classpath
    Function<String,Boolean> check_legacy_classpath = l -> 'forge'==l || (neoforge_legacy_classpath && 'neoforge'==l)

    setCommonRepositories maven_ids
    List<String> loaders = getLoaderList true
    boolean minor_version = isMinorVersion()
    boolean runnable_version = isRunnableVersion()
    dependencies {
        compileOnly project(':api')
        if(runnable_version) {
            parentClasses project(path: ':api', configuration: 'exportClasses')
            if(!isJava8()) {
                forgeLegacyClasspathImplementation libs.bundles.burningwave
                if(neoforge_legacy_classpath) neoforgeLegacyClasspathImplementation libs.bundles.burningwave
            }
        }
        if(minor_version) {
            compileOnly parent
            parentClasses project(path: parent.path, configuration: 'exportClasses')
        }
        tilfabricModImplementation fabricApi.fabric(fabricAPIVersion())
    }
    loaders.forEach {loader ->
        String l_loader = loader.toLowerCase()
        String source_name = "til$l_loader"
        dependencies {
            "${source_name}AnnotationProcessor" libs.lombok
            "${source_name}CompileOnly" project(':api')
            "${source_name}CompileOnly" project(":$l_loader")
            "${source_name}CompileOnly" libs.lombok
            if(minor_version) {
                "parent${loader}Classes"(project(path: parent.path, configuration: "export${loader}Classes"))
                "${source_name}CompileOnly" parent
                "${source_name}CompileOnly" project(path: parent.path, configuration: "$source_name")
            }
            if(runnable_version) {
                "parent${loader}Classes"(project(path: ":$l_loader", configuration: 'exportClasses'))
                "${source_name}ModCompileOnly"(modsBundle(l_loader, 'compile')) {
                    exclude group: 'net.fabricmc'
                }
                "${source_name}ModImplementation"(modsBundle(l_loader, 'implementation')) {
                    exclude group: 'net.fabricmc'
                }
                if(enabled_runtime_mods.contains(l_loader)) {
                    "${source_name}ModRuntimeOnly"(modsBundle(l_loader, 'runtime')) {
                        exclude group: 'net.fabricmc'
                    }
                }
                def mt_versions = enabled_mt[l_loader]
                if(mt_versions!=null && (mt_versions.contains('all') || mt_versions.contains(minecraftVersion())))
                    "${source_name}RuntimeOnly"(libs.musictriggers)
                if(isJava8() || !check_legacy_classpath.apply(l_loader))
                    "${source_name}Implementation" libs.bundles.burningwave
            } else if(isJava8() || !check_legacy_classpath.apply(l_loader))
                "${source_name}Implementation" libs.bundles.burningwave
        }
        tasks.named("${source_name}Classes").configure {
            mustRunAfter 'classes'
        }
        if(minor_version) {
            String p_task = "${parent.path}:inheritParent${loader}Classes"
            tasks.named("compileTil${l_loader}Java").configure {
                mustRunAfter p_task
            }
            tasks.compileJava.mustRunAfter p_task
            tasks.named("inheritParent${loader}Classes").configure {
                mustRunAfter ":${parent.path}:classes"
                mustRunAfter "${parent.path}:${source_name}Classes"
                mustRunAfter ":${l_loader}:classes"
                mustRunAfter ":api:classes"
            }
        } else {
            tasks.named("inheritParent${loader}Classes").configure {
                mustRunAfter ":${l_loader}:classes"
                mustRunAfter ":api:classes"
            }
        }
    }
    tasks.compileJava.mustRunAfter "${parent.path}:classes"
}

void setupForgeLikeConfigs(String loader) {
    configurations {
        def config = create "${loader}LegacyClasspathImplementation"
        [ 'Implementation', 'MinecraftLibraries' ].forEach {config_type ->
            named("til${loader}$config_type").configure {
                extendsFrom config
            }
        }
    }
}

@SuppressWarnings('GrUnresolvedAccess')
void uniminedSetupLoader(SourceSet source, String l_name) {
    unimined.minecraft(source) {
        combineWith sourceSets.main
        boolean is_fabric = 'fabric'==l_name
        if(isRunnableVersion()) {
            boolean forge_like = [ 'forge', 'neoforge' ].contains l_name
            runs {
                if(forge_like) {
                    def build_files = getBuildFiles([main: ['classes\\java'], ("til$l_name".toString()): ['classes\\java', 'resources']])
                    logger.lifecycle "Adding build files to $l_name minecraftLibraries $build_files"
                    configurations.named("til${l_name}MinecraftLibraries").get().dependencies.add dependencies.create(build_files)
                    tasks.named("compileTil${l_name}Java").configure {
                        mustRunAfter "processTil${l_name}Resources"
                    }
                }
                //noinspection ConfigurationAvoidance
                all {
                    javaVersion = getJavaVersionEnum()
                    Map<?,?> map = getSystemProperties()
                    addCustomRunProperties map, "til$l_name"
                    if(forge_like) {
                        [ debug_network, forge_bootstrap_debug ].forEach {debug_prop ->
                            //noinspection GroovyAssignabilityCheck
                            map[debug_prop] = 'true'
                        }
                        addForgeLoggingMarkers map, true
                        setForgeLoggingLevel map, 'debug'
                    }
                }
                if(forge_like) {
                    config('client') {
                        args+=[ '--username', minecraft_username, '--uuid', minecraft_uuid ]
                    }
                }
                config('server') {
                    args+=[ 'nogui' ]
                }
            }
            mods {
                modImplementation {
                    mixinRemap {
                        reset()
                        enableMixinExtra()
                        enableBaseMixin()
                        if(is_fabric) disableRefmap()
                    }
                }
                remap(configurations.named("til${l_name}ModRuntimeOnly").get()) {
                    mixinRemap {
                        reset()
                        enableMixinExtra()
                        enableBaseMixin()
                        if(is_fabric) disableRefmap()
                    }
                }
            }
        } else runs.off = true
        remap(is_fabric ? shadowJar : tasks.named("${l_name}ClassesJar").get()) {
            archiveBaseName = mod_id
            archiveClassifier = "$l_name${is_fabric ? '-relocated-' : '-'}remapped"
            prodNamespace is_fabric ? 'intermediary' : 'searge'
        }
        switch(l_name) {
            case 'fabric' -> {
                fabric {
                    loader project.fabric.versions.loader.get()
                }
            }
            case 'forge' -> {
                minecraftForge {
                    loader modernForgeVersion()
                }
            }
            case 'neoforge' -> {
                neoForge {
                    loader neoforgeVersion()
                }
            }
        }
    }
}

ext.setupShared = this.&setupShared as MethodClosure

@SuppressWarnings('GrUnresolvedAccess')
void setupShared(List<String> extra_maven_ids) {
    setSharedDependencies extra_maven_ids
    addParentProcessedResources()
    setJarsRunAfter collectRunAfter()
    applySourceHelpers()
}