import static org.gradle.api.file.DuplicatesStrategy.EXCLUDE

plugins {
    id 'project-setup-common' //project-setup-common <- project-common-functions <- java-shared
}

//noinspection GrUnresolvedAccess
initJavaPlugin()
//noinspection GrUnresolvedAccess
initShadow()

configurations {
    shaded
    implementation.extendsFrom shaded
}

repositories {
    mavenCentral() {
        content {
            [ toolfactory_group, burningwave_group ].forEach {
                includeGroup it
            }
        }
    }
}

dependencies {
    //noinspection GrUnresolvedAccess
    shaded(libs.bundles.burningwave) { transitive = false }
}

//noinspection GrUnresolvedAccess
shadowJar {
    archiveBaseName = mod_id
    //noinspection GroovyAssignabilityCheck
    configurations = [ project.configurations.shaded ]
    duplicatesStrategy = EXCLUDE
    //noinspection GrUnresolvedAccess
    exclude '**/LICENSE', '**/LICENSE.txt', '**/MANIFEST.*', 'META-INF/maven/**', 'META-INF/*.RSA',
            'META-INF/*.SF', 'META-INF/services/*.Processor', 'META-INF/**/*.class', 'module-info.*'
    //noinspection GrUnresolvedAccess
    mergeServiceFiles()
}