import static org.gradle.api.file.DuplicatesStrategy.EXCLUDE

plugins {
    id 'project-setup-common' //project-setup-common <- project-common-functions <- java-shared
}

initShadedDeps()

@SuppressWarnings('GrUnresolvedAccess')
void initShadedDeps() {
    initJavaPlugin()
    initShadow()
    addShadedDeps()
    configureShadowJar()
}

void addShadedDeps() {
    repositories {
        mavenCentral() {
            content {
                [ toolfactory_group, burningwave_group ].forEach {
                    includeGroup it
                }
            }
        }
    }
    dependencies {
        //noinspection GrUnresolvedAccess
        shadow(libs.bundles.burningwave) { transitive = false }
    }
}

@SuppressWarnings('GrUnresolvedAccess')
void configureShadowJar() {
    shadowJar {
        archiveBaseName = mod_id
        archiveClassifier = 'shaded'
        duplicatesStrategy = EXCLUDE
        exclude '**/LICENSE', '**/LICENSE.txt', '**/MANIFEST.*', 'META-INF/maven/**', 'META-INF/*.RSA',
                'META-INF/*.SF', 'META-INF/services/*.Processor', 'META-INF/**/*.class', 'module-info.*'
        mergeServiceFiles()
    }
}