import org.codehaus.groovy.runtime.MethodClosure

ext.setupIntelliJGenGraph = this.&setupIntelliJGenGraph as MethodClosure
ext.setupJarGraphs = this.&setupJarGraphs as MethodClosure
ext.setupSourceGenGraph = this.&setupSourceGenGraph as MethodClosure

@SuppressWarnings('GrUnresolvedAccess')
String getFullTaskPath(String p_name, String t_name) {
    return "${getFullPath(p_name)}:$t_name"
}

List<String> getIntelliJGenTypes() {
    return switch(name) {
        case '1.12', 'cleanroom', 'fabric', 'forge', 'neoforge' -> [ 'genIntellijRuns' ]
        case 'shared_1.16', 'shared_1.18', 'shared_1.19', 'shared_1.19.2', 'shared_1.19.4', 'shared_1.20.1' ->
            [ 'genIntellijRuns', 'tilfabricGenIntellijRuns', 'tilforgeGenIntellijRuns' ]
        case 'shared_1.20', 'shared_1.20.4', 'shared_1.20.6', 'shared_1.21', 'shared_1.21.1' ->
            [ 'genIntellijRuns', 'tilfabricGenIntellijRuns', 'tilforgeGenIntellijRuns', 'tilneoforgeGenIntellijRuns' ]
        default -> []
    }
}

List<String> getJarParents() {
    return switch(name) {
        case '1.12', 'cleanroom' -> [ 'legacy' ]
        case 'fabric', 'forge', 'legacy', 'neoforge', 'shared' -> [ 'api' ]
        case 'shared_1.16', 'shared_1.18', 'shared_1.19', 'shared_1.20' -> [ 'fabric', 'forge', 'shared' ]
        case 'shared_1.21' -> [ 'fabric', 'forge', 'neoforge', 'shared' ]
        case 'shared_1.20.1' -> [ 'shared_1.20' ]
        case 'shared_1.20.4', 'shared_1.20.6' -> [ 'neoforge', 'shared_1.20' ]
        case 'shared_1.21.1' -> [ 'shared_1.21' ]
        default -> parent==null ? [ '1.12', 'shared_1.16', 'shared_1.18', 'shared_1.19.2', 'shared_1.19.4',
                                       'shared_1.20.1', 'shared_1.20.4', 'shared_1.20.6', 'shared_1.21.1' ] : []
    }
}

List<String> getPreviousGenFabricIntelliJRuns() {
    return switch(name) {
        case 'shared_1.19.2', 'shared_1.19.4' -> [ 'shared_1.16', 'shared_1.18', 'shared_1.19' ]
        case 'shared_1.20.1', 'shared_1.20.4', 'shared_1.20.6' -> [ 'shared_1.16', 'shared_1.18', 'shared_1.20' ]
        case 'shared_1.21.1' -> [ 'shared_1.16', 'shared_1.18', 'shared_1.21' ]
        default -> []
    }
}

@SuppressWarnings('unused')
List<String> getPreviousGenFabricSources(boolean exclude_problematic_versions) {
    return switch(name) {
        case 'shared_1.19.2', 'shared_1.19.4' -> [ 'shared_1.19' ]
        case 'shared_1.20.1', 'shared_1.20.4', 'shared_1.20.6' -> [ 'shared_1.20' ]
        case 'shared_1.21.1' -> [ 'shared_1.21' ]
        default -> parent==null ? [ 'shared_1.16', 'shared_1.18', 'shared_1.19.2', 'shared_1.19.4', 'shared_1.20.1',
                                    'shared_1.20.4', 'shared_1.20.6', 'shared_1.21.1' ] : []
    }
}

List<String> getPreviousGenForgeIntelliJRuns() {
    return switch(name) {
        case 'shared_1.19.2', 'shared_1.19.4' -> [ 'shared_1.16', 'shared_1.18', 'shared_1.19' ]
        case 'shared_1.20.1', 'shared_1.20.4', 'shared_1.20.6' -> [ 'shared_1.16', 'shared_1.18', 'shared_1.20' ]
        case 'shared_1.21.1' -> [ 'shared_1.16', 'shared_1.18', 'shared_1.21' ]
        default -> []
    }
}

List<String> getPreviousGenForgeSources(boolean exclude_problematic_versions) {
    return switch(name) {
        case 'shared_1.19.2', 'shared_1.19.4' -> [ 'shared_1.19' ]
        case 'shared_1.20.1', 'shared_1.20.4', 'shared_1.20.6' -> [ 'shared_1.20' ]
        case 'shared_1.21.1' -> [ 'shared_1.21' ]
        default -> parent==null ? (exclude_problematic_versions ? [ 'shared_1.18', 'shared_1.19.2', 'shared_1.19.4',
                  'shared_1.20.1', 'shared_1.20.4', 'shared_1.20.6', 'shared_1.21.1' ] : [ 'shared_1.16', 'shared_1.18',
                  'shared_1.19.2', 'shared_1.19.4', 'shared_1.20.1', 'shared_1.20.4', 'shared_1.20.6',
                  'shared_1.21.1' ]) : []
    }
}

List<String> getPreviousGenIntelliJRuns() {
    return switch(name) {
        case 'cleanroom' -> [ '1.12' ]
        case 'fabric', 'forge', 'neoforge' -> [ 'cleanroom' ]
        case 'shared_1.16', 'shared_1.18', 'shared_1.19', 'shared_1.20', 'shared_1.21' ->
            [ 'fabric', 'forge', 'neoforge' ]
        case 'shared_1.19.2' -> [ 'shared_1.16', 'shared_1.18', 'shared_1.19' ]
        case 'shared_1.19.4' -> [ 'shared_1.19.2' ]
        case 'shared_1.20.1' -> [ 'shared_1.16', 'shared_1.18', 'shared_1.20' ]
        case 'shared_1.20.4' -> [ 'shared_1.19.4', 'shared_1.20.1' ]
        case 'shared_1.20.6' -> [ 'shared_1.20.4' ]
        case 'shared_1.21.1' -> [ 'shared_1.20.6' ]
        default -> []
    }
}

List<String> getPreviousGenIntelliJRunsByType(String type) {
    if(type==null) return getPreviousGenIntelliJRuns()
    switch(type) {
        case 'tilfabricGenIntellijRuns' -> getPreviousGenFabricIntelliJRuns()
        case 'tilforgeGenIntellijRuns' -> getPreviousGenForgeIntelliJRuns()
        case 'tilneoforgeGenIntellijRuns' -> getPreviousGenNeoforgeIntelliJRuns()
        default -> getPreviousGenIntelliJRuns()
    }
}

List<String> getPreviousGenNeoforgeIntelliJRuns() {
    return switch(name) {
        case 'shared_1.20.4', 'shared_1.20.6' -> [ 'shared_1.20' ]
        case 'shared_1.21.1' -> [ 'shared_1.21' ]
        default -> []
    }
}

@SuppressWarnings('unused')
List<String> getPreviousGenNeoforgeSources(boolean exclude_problematic_versions) {
    return switch(name) {
        case 'shared_1.20.4', 'shared_1.20.6' -> [ 'shared_1.20' ]
        case 'shared_1.21.1' -> [ 'shared_1.21' ]
        default -> parent==null ? [ 'shared_1.20.4', 'shared_1.20.6', 'shared_1.21.1' ] : []
    }
}

List<String> getPreviousGenSources(boolean exclude_problematic_versions) {
    return switch(name) {
        case 'cleanroom' -> [ '1.12' ]
        case 'shared_1.16', 'shared_1.18', 'shared_1.19' ->
            exclude_problematic_versions ? [ 'fabric' ] : [ 'fabric', 'forge' ]
        case 'shared_1.20', 'shared_1.21' ->
            exclude_problematic_versions ? [ 'fabric', 'neoforge' ] : [ 'fabric', 'forge', 'neoforge' ]
        case 'shared_1.19.2', 'shared_1.19.4' -> [ 'shared_1.19' ]
        case 'shared_1.20.1', 'shared_1.20.4', 'shared_1.20.6' -> [ 'shared_1.20' ]
        case 'shared_1.21.1' -> [ 'shared_1.21' ]
        default -> parent==null ? [ 'cleanroom', 'shared_1.16', 'shared_1.18', 'shared_1.19.2', 'shared_1.19.4',
                                    'shared_1.20.1', 'shared_1.20.4', 'shared_1.20.6', 'shared_1.21.1' ] : []
    }
}

List<String> getPreviousGenSourcesByType(String type, boolean exclude_problematic_versions) {
    if(type==null) return getPreviousGenSources(exclude_problematic_versions)
    switch(type) {
        case 'tilfabricGenSources' -> getPreviousGenFabricSources(exclude_problematic_versions)
        case 'tilforgeGenSources' -> getPreviousGenForgeSources(exclude_problematic_versions)
        case 'tilneoforgeGenSources' -> getPreviousGenNeoforgeSources(exclude_problematic_versions)
        default -> getPreviousGenSources(exclude_problematic_versions)
    }
}

List<String> getSourceGenTypes(boolean exclude_problematic_versions) {
    return switch(name) {
        case '1.12', 'cleanroom', 'fabric', 'neoforge' -> [ 'genSources' ]
        case 'forge' -> exclude_problematic_versions ? [] : [ 'genSources' ]
        case 'shared_1.16' -> exclude_problematic_versions ? [ 'genSources', 'tilfabricGenSources' ] :
                [ 'genSources', 'tilfabricGenSources', 'tilforgeGenSources' ]
        case 'shared_1.18', 'shared_1.19', 'shared_1.19.2', 'shared_1.19.4', 'shared_1.20.1' ->
            [ 'genSources', 'tilfabricGenSources', 'tilforgeGenSources' ]
        case 'shared_1.20', 'shared_1.20.4', 'shared_1.20.6', 'shared_1.21', 'shared_1.21.1' ->
            [ 'genSources', 'tilfabricGenSources', 'tilforgeGenSources', 'tilneoforgeGenSources' ]
        default -> parent==null ? [ 'genAllSources' ] : []
    }
}

void setupIntelliJGenGraph() {
    logger.lifecycle "Setting up IntelliJ gen graph for $name"
    getIntelliJGenTypes().forEach {gen_type ->
        tasks.named(gen_type) {gen_task ->
            getPreviousGenIntelliJRunsByType(gen_type).forEach {p_name ->
                gen_task.mustRunAfter getFullTaskPath(p_name, gen_type)
                if(gen_type!='genIntellijRuns')
                    gen_task.mustRunAfter getFullTaskPath(p_name, 'genIntellijRuns')
            }
        }
    }
    logger.lifecycle "Finished setting up IntelliJ gen graph for $name"
}

@SuppressWarnings('GrUnresolvedAccess')
void setupJarGraph(String t_name, String p_t_name) {
    String export_name = p_t_name.replace 'parent', 'export'
    if(parent!=null) {
        createConfiguration export_name, true, false
        artifacts.add export_name, tasks.named(t_name)
    }
    List<String> p_names = getJarParents()
    if(p_names.isEmpty()) return
    createConfiguration p_t_name, false, true
    TaskProvider<Task> provider = tasks.named t_name
    p_names.forEach {p_name ->
        String p_path = getFullPath p_name
        dependencies {
            "$p_t_name" project(path: p_path, configuration: export_name)
        }
        provider.configure {
            dependsOn "$p_path:$t_name"
        }
    }
    provider.configure {
        doFirst {
            configurations.named(p_t_name).get().files.forEach {file ->
                from zipTree(file)
            }
        }
    }
}

void setupJarGraphs() {
    [ 'javadocJar': 'parentJavadocJar', 'sourcesJar': 'parentSourcesJar' ].forEach {t_name, p_t_name ->
        setupJarGraph t_name, p_t_name
    }
}

void setupProblematicSourceGenGraph() {
    logger.lifecycle "Setting up problematic source gen graph"
    def problematic_source_gens = [ ':forge': 'genSources', ':shared:shared_1.16': 'tilforgeGenSources' ]
    tasks.register('genProblematicSources') {
        it.dependsOn 'genAllSources'
    }
    problematic_source_gens.forEach {p_name,t_name ->
        tasks.genProblematicSources.dependsOn "$p_name:$t_name"
        project(p_name).tasks.named(t_name) {
            it.mustRunAfter project.tasks.genAllSources
        }
    }
}

/**
 * Setup dependency ordering for genSources, tilfabricGenSources, tilforgeGenSources, and tilneoforgeGenSources.
 * Use exclude_problematic_versions to exclude tasks from the graph that are known to cause problematic.
 * Register the genAllSources task if necessary.
 */
void setupSourceGenGraph() {
    logger.lifecycle "Setting up source gen graph for $name"
    boolean exclude_problematic_versions = Boolean.parseBoolean filter_problematic_auto_source_gen
    getSourceGenTypes(exclude_problematic_versions).forEach {gen_type ->
        boolean gen_all = 'genAllSources'==gen_type
        tasks."${gen_all ? 'register' : 'named'}"(gen_type) {Task gen_task ->
            (gen_all ? [ 'tilfabricGenSources', 'tilforgeGenSources', 'genSources', 'tilneoforgeGenSources' ] : [ gen_type ]).forEach {sub_gen ->
                getPreviousGenSourcesByType(sub_gen, exclude_problematic_versions).forEach {p_name ->
                    gen_task.dependsOn getFullTaskPath(p_name, sub_gen)
                }
            }
        }
    }
    if(name==null && exclude_problematic_versions) setupProblematicSourceGenGraph()
    logger.lifecycle "Finished setting up source gen graph for $name"
}