/**
 * BUILD WORKFLOW
 *
 * Main project:
 *      1: Setup separate configurations for importing subproject classes & resources as depedencies
 *      2: Avoid duplicates by only importing subprojects with unique classes or resources
 *      3: Ensure the dependency graph is properly setup for the jar task
 *      4: Use Shadow to relocate included API dependencies
 *      5: Set up dependency graph for sourcesJar & javadocJar tasks
 *
 * Sub Projects:
 *      1: Disable the local jar task unless it is necessary for remapping
 *      2: Setup separate configurations for importing parent classes & resources as depedencies
 *      3: Setup separate configurations for exporting classes & resources as artifacts
 *      3: Collect all necessary classes & resources from parents to ensure the run tasks are functional
 *      4: Use Shadow to duplicate shared classes for separate forge/fabric mappings
 *      5: Ensure classes are remapped before being exported to the main project for building
 */

/*
 * External Plugin List
 *
 * - Gradle Doctor
 *      + [id] com.osacky.doctor
 *      + [docs] https://runningcode.github.io/gradle-doctor/
 *      + [desc] Helps to diagnose build performance issues & can only be applied in the root project
 *
 * - Shadow
 *      + [id] com.gradleup.shadow
 *      + [docs] https://gradleup.com/shadow/
 *      + [desc] FatJar builder & package relocator
 *
 * - Unimined
 *      + [id] unimined
 *      + [docs] https://github.com/unimined/Unimined/blob/main/Writerside/topics/starter-topic.md
 *      + [desc] Minecraft provider & remapper
 */
plugins {
    alias libs.plugins.doctor
    id 'shaded-deps'
}

addParentProcessedResources()
createClassesImport 'apiClasses', 'gatherAllClasses', 'classes', 'main'
createConfiguration 'processedClasses', false, true

dependencies {
    apiClasses project(path: ':api', configuration: 'exportClasses')
}

shadowJar {
    configurations = [ 'apiClasses', 'processedClasses', 'shadow' ].collect {c_name ->
        project.configurations.named(c_name).get()
    }
    dependsOn 'classes'
}

[ '1.12', 'shared_1.16', 'shared_1.18', 'shared_1.19.2', 'shared_1.19.4', 'shared_1.20.1', 'shared_1.20.4',
  'shared_1.20.6', 'shared_1.21.1' ].forEach {included_project ->
    String p_path = getFullPath included_project
    dependencies {
        processedClasses project(path: p_path, configuration: 'processedClasses')
    }
    shadowJar.dependsOn "$p_path:${'1.12'==included_project ? 'remap' : 'combined'}ClassesJar"
}

tasks.register('fixManifest', Jar) {
    dependsOn shadowJar
    archiveBaseName = mod_id
    archiveClassifier = ''
    doFirst {
        from zipTree(tasks.named('shadowJar', Jar).get().archiveFile.get())
        manifest {
            attributes([
                    'FMLCorePlugin': legacy_entrypoint,
                    'FMLCorePluginContainsFMLMod': true,
                    'ForceLoadAsMod': true,
                    'Implementation-Title': mod_name,
                    'Implementation-Version': mod_version,
                    'TILMultiversionCoreMods': core_entrypoint,
                    'TILMultiversionMods': common_entrypoint
            ])
        }
    }
}

tasks.assemble.dependsOn fixManifest
tasks.gatherAllClasses.dependsOn ':api:classes'
tasks.shadowJar.finalizedBy fixManifest

//noinspection GrUnresolvedAccess
applySourceHelpers()