/**
 * BUILD WORKFLOW
 *
 * Main project:
 *      1: Apply shadow plugin
 *      2: Apply the functions & shared scripts
 *      3: Do some preliminary setup for the jar & shadowJar tasks
 *
 * Sub Projects:
 *      [BEFORE EVALUATING]
 *          1: Apply the functions & shared scripts
 *
 *      [AFTER EVALUATING]
 *          1: Wait until all sub projects finish building before running the main project jar task
 *          2: Each subproject with loader sources has it's build task run after the relevant source jar tasks
 *          3: Each jar task must do any necessary remapping in the relevant sub project
 *          4: Inherit resources from the fabric sub project (which inherits from the api sub project)
 *          5: Finalize the jar task with shadowJar
 *          6: Collect the contents of all sub project jars in the shadowJar task
 *          7: Do any necessary relocations & exclusions for shading before finalizing the jar
 *          8: Add all relevant sub project classpaths the javadoc task
 *          9: Include all content from sub project javadoc and source jars in the relevant main project jars
 */
plugins {
    alias libs.plugins.shadow
}

apply from: rootProject.file('gradle\\scripts\\functions.gradle')
extendFrom 'shadow'

def main_project = project

subprojects {sub ->
    sub.apply from: rootProject.file('gradle\\scripts\\functions.gradle')
    //noinspection GrUnresolvedAccess
    sub.extendFrom 'shared'
    sub.afterEvaluate {sub_final ->
        //noinspection GroovyAssignabilityCheck
        main_project.jar.mustRunAfter getTaskPath(sub_final.name, 'build')
        main_project.shadowJar { //Add loader sources to the final jar
            //noinspection GrUnresolvedAccess
            def archive_tasks = sub_final.mappingStyleOfficial() ? [ 'jar' ] : [ 'remapJar' ]
            if(isProjectShared(sub_final)) {
                //noinspection GrUnresolvedAccess
                archive_tasks = sub_final.mappingStyleOfficial() ? [ 'jar', 'fabricJar', 'forgeJar' ] :
                        [ 'shadowJar', 'remapForgeJar' ]
                if(isProjectNeoforgeCompatible(sub_final)) {
                    //noinspection GrUnresolvedAccess
                    archive_tasks+=(sub_final.mappingStyleOfficial() || sub_final.name=='shared_1.20.4' ?
                            'neoforgeJar' : 'remapNeoforgeJar')
                }
            } else if(sub_final.name in [ 'api', 'legacy', 'neoforge', 'shared' ]) archive_tasks = [ 'jar' ]
            archive_tasks.forEach {archive_task ->
                //noinspection GrUnresolvedAccess
                from(getArchiveTaskFile(sub_final, archive_task).collect{entry ->
                    zipTree entry
                })
            }
        }
        main_project.javadoc {
            classpath+=classpathCompile(sub_final, 'main')
            if(isProjectShared(sub_final)) {
                classpath+=classpathCompile(sub_final, 'fabric')
                classpath+=classpathCompile(sub_final, 'forge')
                if(isProjectNeoforgeCompatible(sub_final))
                    classpath+=classpathCompile(sub_final, 'neoforge')
            }
        }
        main_project.javadocJar {
            //noinspection GroovyAssignabilityCheck
            mustRunAfter getTaskPath(sub_final.name, 'javadocJar')
            from(getArchiveTaskFile(sub_final, 'javadocJar').collect{entry ->
                zipTree entry
            })
        }
        main_project.sourcesJar {
            //noinspection GroovyAssignabilityCheck
            mustRunAfter getTaskPath(sub_final.name, 'sourcesJar')
            from(getArchiveTaskFile(sub_final, 'sourcesJar').collect{entry ->
                zipTree entry
            })
        }
        if('fabric'==sub_final.name) {
            main_project.processResources {
                from getTaskOutputs(sub_final, 'processResources')
            }
            main_project.processTestResources {
                from getTaskOutputs(sub_final, 'processTestResources')
            }
        }
    }
}

jar {
    manifest {
        attributes([
                'FMLCorePlugin': legacy_entrypoint,
                'FMLCorePluginContainsFMLMod': true,
                'ForceLoadAsMod': true,
                'Implementation-Title': mod_name,
                'Implementation-Version': mod_version,
                'TILMultiversionCoreMods': core_entrypoint,
                'TILMultiversionMods': common_entrypoint
        ])
    }
    finalizedBy shadowJar
}

shadowJar {
    mergeServiceFiles()
    //noinspection GrUnresolvedAccess
    exclude '**/LICENSE', '**/LICENSE.txt', 'META-INF/MANIFEST.MF', 'META-INF/maven/**', 'META-INF/*.RSA',
            'META-INF/*.SF', 'META-INF/services/*.Processor', 'META-INF/**/*.class', 'module-info.*'
}