############################ ARGS ############################

# Gradle Args
# TODO full configuration audit is needed
# Unimined is not compatible with the Configuration Cache yet
org.gradle.configuration-cache=false
org.gradle.configureondemand=true
org.gradle.jvmargs=-Xms2G -Xmx12G

# Other Args
build_file=build\\libs\\theimpossiblelibrary-0.4.6.jar
build_classes=build\\classes\\java\\main
classpath_arg=til.classpath.file
cleanroom_dump=foundation.dump
cleanroom_verbose=foundation.verbose
common_entrypoint_arg=til.classpath.mods
core_entrypoint_arg=til.classpath.coremods
dev_arg=til.dev
dev_sources=til.dev.sources
experimental_setup=true
fabric_log_level=fabric.log.level
filter_problematic_auto_source_gen=true
forge_log_level=forge.logging.console.level
forge_log_markers_values=SCAN,REGISTRIES,REGISTRYDUMP
forge_log_markers_arg=forge.logging.markers
meta_inf_path=src/main/resources/META-INF

######################### UNIVERSALS #########################

# Mod Constants
mod_authors=The_Computerizer
mod_description=Impossible!
mod_id=theimpossiblelibrary
mod_license=LGPL V3.0
mod_mixin=mixins.theimpossiblelibrary.json
mod_name=The Impossible Library
mod_refmap=theimpossiblelibrary.refmap.json
mod_tweakclass=org.spongepowered.asm.launch.MixinTweaker
mod_version=0.4.6

# Dependency Groups, Names, & Plugins
burningwave_group=org.burningwave
lombok_group=org.projectlombok
toolfactory_group=io.github.toolfactory

# Entrypoints
common_entrypoint=mods.thecomputerizer.theimpossiblelibrary.api.common.TILCommonEntryPoint
core_entrypoint=mods.thecomputerizer.theimpossiblelibrary.api.core.TILCoreEntryPoint
fabric_adaptor=mods.thecomputerizer.theimpossiblelibrary.fabric.core.TILLanguageAdaptorFabric
fabric_injector=mods.thecomputerizer.theimpossiblelibrary.fabric.core.loader.TILModInjectorFabric
forge_entrypoint=mods.thecomputerizer.theimpossiblelibrary.forge.core.MultiVersionModLocator
legacy_entrypoint=mods.thecomputerizer.theimpossiblelibrary.legacy.v12.m2.core.TILLoadingPlugin1_12_2
neoforge_entrypoint=mods.thecomputerizer.theimpossiblelibrary.neoforge.core.MultiVersionModLocator

# Mod Packages
api_package=mods.thecomputerizer.theimpossiblelibrary.api
base_package=mods.thecomputerizer.theimpossiblelibrary
shadow_package=mods.thecomputerizer.shadow

############################## CONTENT ##############################

settings_plugin_content=at.favre.lib;\
  com.fasterxml;\
  com.fasterxml.jackson;\
  com.fasterxml.woodstox;\
  com.github.hypfvieh;\
  com.github.javakeyring;\
  com.github.jnr;\
  com.github.jponge;\
  com.github.spotbugs;\
  com.google.code.findbugs;\
  com.google.code.gson;\
  com.google.errorprone;\
  com.google.guava;\
  com.google.j2objc;\
  com.gradleup.shadow;\
  com.googlecode.javaewah;\
  com.nothome;\
  com.osacky.doctor;\
  com.salesforce.maven;\
  com.squareup.okio;\
  com.sschr15.annotations;\
  commons-codec;\
  commons-io;\
  de.swiesend;\
  io.github.oshai;\
  io.jsonwebtoken;\
  io.reactivex.rxjava3;\
  io.sigpipe;\
  jakarta.platform;\
  net.java.dev.jna;\
  net.lenni0451.commons;\
  net.raphimc;\
  net.sf.jopt-simple;\
  org.apache;\
  org.apache.ant;\
  org.apache.commons;\
  org.apache.groovy;\
  org.apache.logging;\
  org.apache.logging.log4j;\
  org.apache.maven;\
  org.checkerframework;\
  org.codehaus.plexus;\
  org.codehaus.woodstox;\
  org.eclipse.ee4j;\
  org.eclipse.jgit;\
  com.gradle;\
  org.gradle.toolchains;\
  org.gradle.toolchains.foojay-resolver-convention;\
  org.jdom;\
  org.jetbrains;\
  org.jetbrains.kotlin;\
  org.jetbrains.kotlinx;\
  org.junit;\
  org.mockito;\
  org.ow2;\
  org.ow2.asm;\
  org.reactivestreams;\
  org.slf4j;\
  org.sonatype.oss;\
  org.springframework;\
  org.vafer;\
  pt.davidafsilva.apple;\
  trove

unimined_releases=net.fabricmc;\
  net.minecraftforge;\
  net.neoforged;\
  xyz.wagyourtail.commons;\
  xyz.wagyourtail.unimined.mapping

unimined_snapshots=xyz.wagyourtail.commons;\
  xyz.wagyourtail.unimined;\
  xyz.wagyourtail.unimined.mapping