pluginManagement {
    repositories {
        gradlePluginPortal() {
            content {
                settings_plugin_content.split(';').each {grp ->
                    includeGroup grp
                }
                unimined_plugin_portal.split(';').each {grp ->
                    includeGroup grp
                }
            }
        }
        maven {
            name = 'WagYourMaven Releases'
            url = uri 'https://maven.wagyourtail.xyz/releases'
            content {
                unimined_releases.split(';').each {grp ->
                    includeGroup grp
                }
            }
        }
        maven {
            name = 'WagYourMaven Snapshots'
            url = uri 'https://maven.wagyourtail.xyz/snapshots'
            content {
                unimined_snapshots.split(';').each {grp ->
                    includeGroup grp
                }
            }
        }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.+'
}

rootProject.name = 'The_Impossible_Library'

def paths = [ ':api', ':fabric', ':forge', ':neoforge', ':legacy:1.12', ':legacy:cleanroom', ':shared:1.16',
        ':shared:1.18', ':shared:1.19', ':shared:1.20', ':shared:1.21', ':shared:1.19:1.19.2', ':shared:1.19:1.19.4',
        ':shared:1.20:1.20.1', ':shared:1.20:1.20.4', ':shared:1.20:1.20.6', ':shared:1.21:1.21.1' ]

paths.forEach {
    include it
}


paths.forEach {
    String[] split = (it.startsWith(':') ? it.substring(1) : it).split(':')
    String name = split.first()
    if(split.length>1) {
        String last = split.last()
        if(name=='api' || name=='cleanroom' || name=='legacy') name = last
        else name = name+"_"+last
    }
    findProject(it)?.name = name
}