import static org.gradle.api.file.DuplicatesStrategy.EXCLUDE

plugins.apply 'idea'
plugins.apply 'java'
plugins.apply 'java-library'

group = base_package
version = mod_version

compileJava {
    options.encoding = 'UTF-8'
}

idea {
    module {
        downloadJavadoc = true
        downloadSources = true
    }
}

jar {
    duplicatesStrategy = EXCLUDE
    setArchiveBaseName "$mod_id"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of 17
    withSourcesJar()
    withJavadocJar()
}

processResources {
    duplicatesStrategy = EXCLUDE
}

javadocJar {
    duplicatesStrategy = EXCLUDE
    setArchiveBaseName "$mod_id"
}

sourcesJar {
    duplicatesStrategy = EXCLUDE
    setArchiveBaseName "$mod_id"
}