//file:noinspection GroovyAssignabilityCheck

/**
 * Shared implementations for 1.16
 */
def base = project ':api'
def fabric_base = project ':fabric'
def forge_base = project ':forge'
def shared = project ':shared'

repositories {
    maven {
        name = 'Modding Legacy'
        url = uri 'https://maven.moddinglegacy.com/maven'
        content {
            includeGroup 'com.legacy'
        }
    }
}

shadowJar {
    [ base, fabric_base, forge_base, shared ].forEach {
        from(it.jar.archiveFile.collect { zipTree it })
    }
    shadowJar.finalizedBy 'remapJar'
}

tasks.assemble.dependsOn shadowJar