//file:noinspection GroovyAssignabilityCheck

/**
 * Shared implementations for 1.16
 */
plugins {
    alias libs.plugins.shadow
    alias libs.plugins.unimined
}

extendFrom project, 'shadow'

uniminedCommon project
uniminedFabric project, true
uniminedForge project, true

repositories {
    maven {
        name = 'Modding Legacy'
        url = uri 'https://maven.moddinglegacy.com/maven'
        content {
            includeGroup 'com.legacy'
        }
    }
}