/**
 * Shared implementations for 1.16
 */
plugins {
    alias libs.plugins.shadow
    alias libs.plugins.unimined
}

extendFrom 'shadow'

uniminedCommon()
uniminedFabric true
uniminedForge true

setSharedDependencies false, false, 'cf', 'ct', 'jei', 'legacy', 'modrinth', 'modmenu'

inheritResources ':shared'

setJarsRunAfter true, ':shared'