modLoader="javafml"
loaderVersion="[39,)"
license="All Rights Reserved"
showAsResourcePack=false

[[mods]]
modId="theimpossiblelibrary"
version="1.18.2-0.1.9"
displayName="The Impossible Library"
updateJSONURL=""
displayURL="https://www.curseforge.com/minecraft/mc-mods/the-impossible-library"
logoFile="logo"
credits="The_Computerizer"
authors="The_Computerizer"
description='''
      Impossible!
      '''

[[dependencies.theimpossiblelibrary]]
modId="forge"
mandatory=true
versionRange="[39,)"
ordering="NONE"
side="BOTH"

[[dependencies.theimpossiblelibrary]]
modId="minecraft"
mandatory=true
versionRange="[1.18.1,1.19)"
ordering="NONE"
side="BOTH"