modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
showAsResourcePack=false

[[mods]]
    modId="theimpossiblelibrary"
    version="${version}"
    displayName="The Impossible Library"
    updateJSONURL=""
    displayURL="https://www.curseforge.com/minecraft/mc-mods/the-impossible-library"
    logoFile="logo.png"
    credits="The_Computerizer"
    authors="The_Computerizer"
    description='''
          Impossible!
          '''

    [[dependencies.theimpossiblelibrary]]
        modId="forge"
        mandatory=true
        versionRange="[43,)"
        ordering="NONE"
        side="BOTH"

    [[dependencies.theimpossiblelibrary]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.19.2,1.20)"
        ordering="NONE"
        side="BOTH"