/**
 * Forge implementation for 1.16.5
 */
//file:noinspection GroovyAssignabilityCheck
buildscript {
    repositories {
        gradlePluginPortal() {
            content {
                plugin_portal_content.split(';').each {grp ->
                    includeGroup grp
                }
            }
        }
        maven {
            name = 'Forge'
            url = uri 'https://maven.minecraftforge.net/'
            content {
                forge_content.split(';').each {grp ->
                    includeGroup grp
                }
            }
        }
        maven {
            name = 'ParchmentMC'
            url = uri 'https://maven.parchmentmc.org'
            content {
                parchment_content.split(';').each {grp ->
                    includeGroup grp
                }
            }
        }
    }
    dependencies {
        classpath "$shadow_plugin:$shadow_version"
        classpath "$forge_gradle_plugin:$forge_gradle_version"
        classpath "$parchment_plugin:$parchment_plugin_version"
    }
}

apply from: rootProject.file('gradle\\java8-module.gradle')

plugins.apply 'net.minecraftforge.gradle'
plugins.apply 'org.parchmentmc.librarian.forgegradle'

def base = project ':api'
def forge = project ':forge'
def shared = project ':shared:shared_1.16'

def classpath_file = "$mod_id-${mod_version}_mapped_parchment_$parchment_1_16_5-${minecraft_1_16_5}.jar"

minecraft {
    copyIdeResources = true
    mappings channel: 'parchment', version: "$parchment_1_16_5-$minecraft_1_16_5"
    runs {
        def runSources = [ sourceSets.main ]
        def args = [ dev_arg, "$classpath_arg$classpath_file".toString(), common_entrypoint_arg, core_entrypoint_arg ]
        configureEach {
            def srgToMcpFile = project.tasks.createSrgToMcp.outputs.files[0].path
            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.console.level', forge_log_level
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', srgToMcpFile
            property 'net.minecraftforge.gradle.GradleStart.srg.srg-mcp', srgToMcpFile
            setSources runSources
            jvmArgs args
        }
        client {
            workingDirectory file('run_client')
        }
        server {
            workingDirectory file('run_server')
        }
    }
}

repositories {
    maven {
        name = 'CurseMaven'
        url = uri 'https://www.cursemaven.com'
        content {
            includeGroup 'curse.maven'
        }
    }
    maven {
        name = 'BlameJared'
        url = uri 'https://maven.blamejared.com'
        content {
            [ 'bookshelf', 'gamestages' ].forEach {includeGroup "net.darkhax.$it" }
        }
    }
    maven {
        name = 'Modding Legacy'
        url = uri 'https://maven.moddinglegacy.com/maven'
        content {
            includeGroup 'com.legacy'
        }
    }
    maven {
        name = 'ModMaven'
        url = uri 'https://modmaven.dev'
        content {
            includeGroup 'mezz.jei'
        }
    }
}

dependencies {
    //noinspection VulnerableLibrariesLocal
    minecraft "$forge_mc:$forge_1_16_5"

    compileOnlyApi base
    compileOnlyApi project(path: ':forge', configuration: 'dev')
    compileOnlyApi shared

    //mod support dependencies
    implementation fg.deobf("$betterweather_artifact:$betterweather_1_16_5")
    implementation fg.deobf("$blueskies_artifact:$blueskies_1_16_5")
    implementation fg.deobf("$bookshelf_artifact-$bookshelf_1_16_5")
    implementation fg.deobf("$champions_artifact:$champions_1_16_5")
    implementation fg.deobf("$configured_artifact:$configured_1_16_5")
    implementation fg.deobf("$dynamic_surroundings_artifact:$dynamic_surroundings_1_16_5")
    implementation fg.deobf("$enhanced_celestials_artifact:$enhanced_celestials_1_16_5")
    implementation fg.deobf("$game_stages_artifact-$game_stages_1_16_5")
    implementation fg.deobf("$serene_seasons_artifact:$serene_seasons_1_16_5")
    implementation fg.deobf("$structure_gel_api_artifact:$structure_gel_api_1_16_5")

    runtimeOnly fg.deobf("$jei_artifact:$jei_1_16_5")
}

jar {
    manifest {
        attributes([
                'Implementation-Version': mod_version
        ])
    }
}

reobf {
    shadowJar {
        dependsOn createMcpToSrg
        mappings = createMcpToSrg.output
    }
}

shadowJar {
    [ base, forge ].forEach {
        from(it.jar.archiveFile.collect { zipTree it })
    }
    shared.afterEvaluate {
        from(shared.jar.archiveFile.collect { zipTree it })
        relocate "$shared_base_package", "$forge_base_package"
    }
}

tasks.assemble.dependsOn shadowJar
tasks.shadowJar.dependsOn 'reobfJar'
tasks.jar.finalizedBy 'reobfJar'
tasks.jar.mustRunAfter ':forge:jar'
tasks.jar.mustRunAfter ':shared:shared_1.16:jar'