/**
 * Java 23 means that this module is in 1.20.6+ and JOML should not be shaded
 */
apply from: rootProject.file('buildSrc\\shared.gradle')

java.toolchain.languageVersion = JavaLanguageVersion.of 21

apply from: rootProject.file('gradle\\lombok.gradle')
apply from: rootProject.file('gradle\\shadow-relocate.gradle')