[bundles]
    cleanroom-compile = [ 'cleanroom-lwjglx', 'cleanroom-mixin' ]
    forge-runtime = [ 'mixinbooter' ]
    mods-1_12_2-compile = [ 'bloodmoon-1_12_2', 'blueskies-1_12_2', 'dsurround-1_12_2', 'gamestages-1_12_2',
        'orelib-1_12_2', 'sereneseasons-1_12_2' ]
    mods-1_12_2-implementation = [ 'bookshelf-1_12_2', 'champions-1_12_2', 'coroutil-1_12_2', 'infernalmobs-1_12_2',
        'nyx-1_12_2', 'weather2-1_12_2' ]
    mods-1_12_2-runtime = [ 'hei-1_12_2' ]
    nothirium = [ 'nothirium-1_12_2', 'renderlib-1_12_2' ]

[libraries]
    bloodmoon-1_12_2 = { group = 'curse.maven', name = 'bloodmoon-226321', version.ref = 'bloodmoon-1_12_2' }
    blueskies-1_12_2 = { group = 'curse.maven', name = 'blueskies-312918', version.ref = 'blueskies-1_12_2' }
    bookshelf-1_12_2 = { group = 'net.darkhax.bookshelf', name = 'Bookshelf-1.12.2', version.ref = 'bookshelf-1_12_2' }
    cleanroom-lwjglx = { group = 'com.cleanroommc', name = 'lwjglx', version.ref = 'cleanroom-lwjglx' }
    cleanroom-mixin = { group = 'com.cleanroommc', name = 'sponge-mixin', version.ref = 'cleanroom-mixin' }
    champions-1_12_2 = { group = 'curse.maven', name = 'champions-307152', version.ref = 'champions-1_12_2' }
    coroutil-1_12_2 = { group = 'curse.maven', name = 'coroutil-237749', version.ref = 'coroutil-1_12_2' }
    dsurround-1_12_2 = { group = 'curse.maven', name = 'dsurround-238891', version.ref = 'dsurround-1_12_2' }
    gamestages-1_12_2 = { group = 'net.darkhax.gamestages', name = 'GameStages-1.12.2', version.ref = 'gamestages-1_12_2' }
    hei-1_12_2 = { group = 'mezz', name = 'jei', version.ref = 'hei-1_12_2' }
    infernalmobs-1_12_2 = { group = 'curse.maven', name = 'infernalmobs-227875', version.ref = 'infernalmobs-1_12_2' }
    mixinbooter = { group = 'zone.rong', name = 'mixinbooter', version.ref = 'mixinbooter' }
    nothirium-1_12_2 = { group = 'curse.maven', name = 'nothirium-624960', version.ref = 'nothirium-1_12_2' }
    nyx-1_12_2 = { group = 'curse.maven', name = 'nyx-349214', version.ref = 'nyx-1_12_2' }
    orelib-1_12_2 = { group = 'curse.maven', name = 'orelib-307806', version.ref = 'orelib-1_12_2' }
    renderlib-1_12_2 = { group = 'curse.maven', name = 'renderlib-624967', version.ref = 'renderlib-1_12_2' }
    sereneseasons-1_12_2 = { group = 'curse.maven', name = 'sereneseasons-291874', version.ref = 'sereneseasons-1_12_2' }
    weather2-1_12_2 = { group = 'curse.maven', name = 'weather2-695602', version.ref = 'weather2-1_12_2' }

[versions]
    bloodmoon-1_12_2 = '2537917'        # Bloodmoon (requires mcp folder to run in dev)
    blueskies-1_12_2 = '2827455'        # Blue Skies
    bookshelf-1_12_2 = '2.3.590'        # Bookshelf (Game Stages lib)
    cleanroom-mixin = '0.+'             # Mixin (Cleanroom)
    cleanroom-lwjglx = '1.+'            # LWJGLX (Cleanroom)
    champions-1_12_2 = '3177947'        # Champions
    coroutil-1_12_2 = '2902920'         # CoroUtil (Weather 2 lib)
    dsurround-1_12_2 = '3497269'        # Dynamic Surroundings
    gamestages-1_12_2 = '2.0.123'       # Game Stages
    hei-1_12_2 = '4.28.0'               # Had Enough Items (Just Enough Items)
    infernalmobs-1_12_2 = '3431758'     # AtomicStryker's Infernal Mobs
    mixinbooter = '10.6'                # MixinBooter (Forge)
    nothirium-1_12_2 = '6461211'        # Nothirium (Modern GL)
    nyx-1_12_2 = '3161738'              # Nyx
    orelib-1_12_2 = '2820815'           # OreLib (Dynamic Surroundings lib)
    renderlib-1_12_2 = '6461209'        # RenderLib (Nothirium lib)
    sereneseasons-1_12_2 = '2799213'    # Serene Seasons
    weather2-1_12_2 = '5705205'         # Weather 2 - Remastered