[bundles]
    api-compile = [ 'asm-commons', 'asm-util', 'fastutil', 'google-jsr', 'jetbrains-annotations', 'log4j-core',
        'netty-all' ]
    burningwave = [ 'burningwave-core', 'burningwave-driver', 'toolfactory-driver' ]
    legacy-annotations = [ 'google-gson', 'google-guava' ]


[libraries]
    asm-commons = { group = 'org.ow2.asm', name = 'asm-commons', version.ref = 'asm' }
    asm-util = { group = 'org.ow2.asm', name = 'asm-util', version.ref = 'asm' }
    burningwave-core = { group = 'org.burningwave', name = 'core', version.ref = 'burningwave-core' }
    burningwave-driver = { group = 'org.burningwave', name = 'jvm-driver', version.ref = 'burningwave-driver' }
    fastutil = { group = 'it.unimi.dsi', name = 'fastutil', version.ref = 'fastutil' }
    google-gson = { group = 'com.google.code.gson', name = 'gson', version.ref = 'gson' }
    google-guava = { group = 'com.google.guava', name = 'guava', version.ref = 'guava' }
    google-jsr = { group = 'com.google.code.findbugs', name = 'jsr305', version.ref = 'jsr' }
    jetbrains-annotations = { group = 'org.jetbrains', name = 'annotations', version.ref = 'jetbrains-annotations' }
    log4j-core = { group = 'org.apache.logging.log4j', name = 'log4j-core', version.ref = 'log4j' }
    lombok = { group = 'org.projectlombok', name = 'lombok', version.ref = 'lombok' }
    netty-all = { group = 'io.netty', name = 'netty-all', version.ref = 'netty-all' }
    toolfactory-driver = { group = 'io.github.toolfactory', name = 'jvm-driver', version.ref = 'toolfactory' }

[plugins]
    shadow = { id = 'com.gradleup.shadow', version.ref = 'shadow' }
    unimined = { id = 'xyz.wagyourtail.unimined', version.ref = 'unimined' }

[versions]
    asm = '9.7'
    burningwave-core = '12.+'
    burningwave-driver = '8.+'
    fastutil = '7.1.0'
    gson = '2.8.+'
    guava = '32.1.+'
    jetbrains-annotations = '+'
    jsr = '3.0.+'
    log4j = '2.+'
    lombok = '1.+'
    netty-all = '4.1.114.Final'
    shadow = '9.+'
    toolfactory = '9.+'
    unimined = '1.+'