[bundles]
    api-compile = [ 'asm-commons', 'asm-util', 'fastutil', 'google-jsr', 'jetbrains-annotations', 'log4j-core',
        'netty-all' ]
    burningwave = [ 'burningwave-core', 'burningwave-driver', 'toolfactory-driver' ]
    legacy-annotations = [ 'google-gson', 'google-guava' ]


[libraries]
    asm-commons = { group = 'org.ow2.asm', name = 'asm-commons', version.ref = 'asm' }
    asm-util = { group = 'org.ow2.asm', name = 'asm-util', version.ref = 'asm' }
    burningwave-core = { group = 'org.burningwave', name = 'core', version.ref = 'burningwave-core' }
    burningwave-driver = { group = 'org.burningwave', name = 'jvm-driver', version.ref = 'burningwave-driver' }
    fastutil = { group = 'it.unimi.dsi', name = 'fastutil', version.ref = 'fastutil' }
    google-gson = { group = 'com.google.code.gson', name = 'gson', version.ref = 'gson' }
    google-guava = { group = 'com.google.guava', name = 'guava', version.ref = 'guava' }
    google-jsr = { group = 'com.google.code.findbugs', name = 'jsr305', version.ref = 'jsr' }
    jetbrains-annotations = { group = 'org.jetbrains', name = 'annotations', version.ref = 'jetbrains-annotations' }
    log4j-core = { group = 'org.apache.logging.log4j', name = 'log4j-core', version.ref = 'log4j' }
    musictriggers = { group = 'curse.maven', name = 'musictriggers-518410', version.ref = 'musictriggers' }
    lombok = { group = 'org.projectlombok', name = 'lombok', version.ref = 'lombok' }
    netty-all = { group = 'io.netty', name = 'netty-all', version.ref = 'netty-all' }
    spotbugs-annotations = { group = 'com.github.spotbugs', name = 'spotbugs-annotations', version.ref = 'spotbugs' }
    toolfactory-driver = { group = 'io.github.toolfactory', name = 'jvm-driver', version.ref = 'toolfactory' }

[plugins]
    curseforge = { id = 'net.darkhax.curseforgegradle', version.ref = 'curseforge' }
    doctor = { id = 'com.osacky.doctor', version.ref = 'doctor' }
    modrinth = { id = 'com.modrinth.minotaur', version.ref = 'modrinth' }
    wiki = { id = 'org.moddedmc.wiki.toolkit', version.ref = 'wiki' }

[versions]
    # API Dependency Versions
    asm = '9.7'
    fastutil = '7.1.0'
    jetbrains-annotations = '+'
    jsr = '3.0.+'
    log4j = '2.+'
    netty-all = '4.1.114.Final'

    # Common Dependency Versions
    burningwave-core = '12.+'
    burningwave-driver = '8.+'
    lombok = '1.+'
    musictriggers = '6497407'
    spotbugs = '4.8.6'
    toolfactory = '9.+'

    # Legacy Annotation Versions
    gson = '2.8.9'
    guava = '32.1.3-jre'

    # Minecraft Versions
    minecraft_1_12_2 = '1.12.2'
    minecraft_1_16_5 = '1.16.5'
    minecraft_1_18_2 = '1.18.2'
    minecraft_1_19_2 = '1.19.2'
    minecraft_1_19_4 = '1.19.4'
    minecraft_1_20_1 = '1.20.1'
    minecraft_1_20_4 = '1.20.4'
    minecraft_1_20_6 = '1.20.6'
    minecraft_1_21_1 = '1.21.1'
    minecraft_1_21_3 = '1.21.3'
    minecraft_1_21_4 = '1.21.4'
    minecraft_1_21_5 = '1.21.5'
    minecraft_1_21_6 = '1.21.6'
    minecraft_1_21_7 = '1.21.7'
    minecraft_1_21_8 = '1.21.8'
    minecraft_1_21_9 = '1.21.9'

    # Parchment Versions
    parchment_1_16_5 = '2022.03.06'
    parchment_1_18_2 = '2022.11.06'
    parchment_1_19_2 = '2022.11.27'
    parchment_1_19_4 = '2023.06.26'
    parchment_1_20_1 = '2023.09.03'
    parchment_1_20_4 = '2024.04.14'
    parchment_1_20_6 = '2024.06.16'
    parchment_1_21_1 = '2024.11.17'
    parchment_1_21_3 = '2024.12.07'
    parchment_1_21_4 = '2025.03.23'
    parchment_1_21_5 = '2025.06.15'
    parchment_1_21_6 = '2025.06.29'
    parchment_1_21_7 = '2025.07.18'
    parchment_1_21_8 = '2025.07.20'

    # Plugin Versions
    curseforge = '1.1.+'
    doctor = '0.11.+'
    modrinth = '+'
    wiki = '+'