[bundles]
    mods-1_20_1-compile = []
    mods-1_20_1-implementation = [ 'dataanchor-1_20_1', 'enhancedcelestials-1_20_1' ]
    mods-1_20_1-runtime = []
    mods-1_20_4-compile = []
    mods-1_20_4-implementation = [ 'bookshelf-1_20_4', 'configured-1_20_4', 'glitchcore-1_20_4', 'infernalmobs-1_20_4',
        'sereneseasons-1_20_4' ]
    mods-1_20_4-runtime = [ 'architectury-1_20_4', 'jei-1_20_4' ]
    mods-1_20_6-compile = []
    mods-1_20_6-implementation = [ 'configured-1_20_6', 'glitchcore-1_20_6', 'infernalmobs-1_20_6',
        'sereneseasons-1_20_6' ]
    mods-1_20_6-runtime = [ 'architectury-1_20_6', 'jei-1_20_6' ]
    mods-1_21_1-compile = []
    mods-1_21_1-implementation = [ 'bookshelf-1_21_1', 'configured-1_21_1', 'coroutil-1_21_1', 'dataanchor-1_21_1',
        'enhancedcelestials-1_21_1', 'glitchcore-1_21_1', 'infernalmobs-1_21_1', 'sereneseasons-1_21_1' ]
    mods-1_21_1-runtime = [ 'architectury-1_21_1', 'corgilib-1_21_1', 'jei-1_21_1' ]

[libraries]
    architectury-1_20_4 = { group = 'maven.modrinth', name = 'architectury-api', version.ref = 'architectury-1_20_4' }
    architectury-1_20_6 = { group = 'maven.modrinth', name = 'architectury-api', version.ref = 'architectury-1_20_6' }
    architectury-1_21_1 = { group = 'maven.modrinth', name = 'architectury-api', version.ref = 'architectury-1_21_1' }

    bookshelf-1_20_4 = { group = 'net.darkhax.bookshelf', name = 'Bookshelf-NeoForge-1.20.4', version.ref = 'bookshelf-1_20_4' }
    bookshelf-1_21_1 = { group = 'net.darkhax.bookshelf', name = 'bookshelf-neoforge-1.21.1', version.ref = 'bookshelf-1_21_1' }

    configured-1_20_4 = { group = 'curse.maven', name = 'configured-457570', version.ref = 'configured-1_20_4' }
    configured-1_20_6 = { group = 'curse.maven', name = 'configured-457570', version.ref = 'configured-1_20_6' }
    configured-1_21_1 = { group = 'curse.maven', name = 'configured-457570', version.ref = 'configured-1_21_1' }

    corgilib-1_21_1 = { group = 'curse.maven', name = 'corgilib-693313', version.ref = 'corgilib-1_21_1' }

    coroutil-1_21_1 = { group = 'curse.maven', name = 'coroutil-237749', version.ref = 'coroutil-1_21_1' }

    dataanchor-1_20_1 = { group = 'curse.maven', name = 'dataanchor-1203668', version.ref = 'dataanchor-1_20_1' }
    dataanchor-1_21_1 = { group = 'curse.maven', name = 'dataanchor-1203668', version.ref = 'dataanchor-1_21_1' }

    enhancedcelestials-1_20_1 = { group = 'curse.maven', name = 'enhancedcelestials-438447', version.ref = 'enhancedcelestials-1_20_1' }
    enhancedcelestials-1_21_1 = { group = 'curse.maven', name = 'enhancedcelestials-438447', version.ref = 'enhancedcelestials-1_21_1' }

    glitchcore-1_20_4 = { group = 'curse.maven', name = 'glitchcore-955399', version.ref = 'glitchcore-1_20_4' }
    glitchcore-1_20_6 = { group = 'curse.maven', name = 'glitchcore-955399', version.ref = 'glitchcore-1_20_6' }
    glitchcore-1_21_1 = { group = 'curse.maven', name = 'glitchcore-955399', version.ref = 'glitchcore-1_21_1' }

    infernalmobs-1_20_4 = { group = 'curse.maven', name = 'infernalmobs-227875', version.ref = 'infernalmobs-1_20_4' }
    infernalmobs-1_20_6 = { group = 'curse.maven', name = 'infernalmobs-227875', version.ref = 'infernalmobs-1_20_6' }
    infernalmobs-1_21_1 = { group = 'curse.maven', name = 'infernalmobs-227875', version.ref = 'infernalmobs-1_21_1' }

    jei-1_20_4 = { group = 'mezz.jei', name = 'jei-1.20.4-neoforge', version.ref = 'jei-1_20_4' }
    jei-1_20_6 = { group = 'mezz.jei', name = 'jei-1.20.6-neoforge', version.ref = 'jei-1_20_6' }
    jei-1_21_1 = { group = 'mezz.jei', name = 'jei-1.21.1-neoforge', version.ref = 'jei-1_21_1' }

    sereneseasons-1_20_4 = { group = 'curse.maven', name = 'sereneseasons-291874', version.ref = 'sereneseasons-1_20_4' }
    sereneseasons-1_20_6 = { group = 'curse.maven', name = 'sereneseasons-291874', version.ref = 'sereneseasons-1_20_6' }
    sereneseasons-1_21_1 = { group = 'curse.maven', name = 'sereneseasons-291874', version.ref = 'sereneseasons-1_21_1' }

[versions]
    # Core & Loader Versions
    neoforge_1_20_1 = '47.1.106'
    neoforge_1_20_4 = '249'
    neoforge_1_20_6 = '138'
    neoforge_1_21_1 = '197'
    neoforge_1_21_3 = '87'
    neoforge_1_21_4 = '149'
    neoforge_1_21_5 = '90'
    neoforge_1_21_6 = '20-beta'
    neoforge_1_21_7 = '25-beta'
    neoforge_1_21_8 = '27'

    # Curseforge Dependency Versions
    configured-1_20_4 = '5105024'
    configured-1_20_6 = '5340194'
    configured-1_21_1 = '5873783'

    corgilib-1_21_1 = '6808264'

    coroutil-1_21_1 = '5622966'

    dataanchor-1_20_1 = '6507578'
    dataanchor-1_21_1 = '6507634'

    enhancedcelestials-1_20_1 = '6318263'
    enhancedcelestials-1_21_1 = '6320077'

    glitchcore-1_20_4 = '5088442'
    glitchcore-1_20_6 = '5352264'
    glitchcore-1_21_1 = '5660740'

    infernalmobs-1_20_4 = '5151259'
    infernalmobs-1_20_6 = '5329764'
    infernalmobs-1_21_1 = '5798525'

    sereneseasons-1_20_4 = '5206533'
    sereneseasons-1_20_6 = '5420644'
    sereneseasons-1_21_1 = '6182596'

    # Non Curseforge Dependency Versions
    architectury-1_20_4 = '11.1.17+neoforge'
    architectury-1_20_6 = '12.1.4+neoforge'
    architectury-1_21_1 = '13.0.8+neoforge'

    bookshelf-1_20_4 = '23.1.11'
    bookshelf-1_21_1 = '21.1.10'

    jei-1_20_4 = '17.3.1.5'
    jei-1_20_6 = '18.0.0.66'
    jei-1_21_1 = '19.22.1.316'