configurations {
    implementation.extendsFrom shaded
}

repositories {
    mavenCentral() {
        content {
            [ toolfactory_group, burningwave_group ].forEach {
                includeGroup it
            }
        }
    }
}

dependencies {
    shaded("$burningwave_group:$burningwave_name:$burningwave_version") { transitive = false }
    shaded("$burningwave_group:$burningwave_driver_name:$burningwave_driver_version") { transitive = false }
    shaded("$toolfactory_group:$toolfactory_name:$toolfactory_version") { transitive = false }
}