configurations {
    implementation.extendsFrom shaded
}

repositories {
    mavenCentral() {
        content {
            [ 'io.github.toolfactory', 'org.burningwave', 'org.joml' ].forEach {
                includeGroup it
            }
        }
    }
}

dependencies {
    shaded("org.joml:joml:$joml_version") { transitive = false }
    shaded("$burningwave_group:core:$burningwave_version") { transitive = false }
    shaded("$burningwave_group:jvm-driver:$burningwave_driver_version") { transitive = false }
    shaded("$toolfactory_group:jvm-driver:$toolfactory_version") { transitive = false }
}