/**
 * Handle JOML separately since it is included in 1.19.4+ and should not be relocated
 */
apply from: rootProject.file('gradle\\shadow-relocate.gradle')

repositories {
    mavenCentral() {
        content {
            includeGroup joml_group
        }
    }
}

dependencies {
    shaded("$joml_group:$joml_name:$joml_version") { transitive = false }
}

shadowJar {
    relocate "$joml_group", "$shadow_package.$joml_group"
}