modLoader="javafml"
loaderVersion="${loader_range}"
license="${mod_license}"
showAsResourcePack=false

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    updateJSONURL=""
    displayURL="https://www.curseforge.com/minecraft/mc-mods/the-impossible-library"
    logoFile="logo.png"
    credits="${mod_author}"
    authors="${mod_author}"
    description="${mod_description}"

    [[dependencies.theimpossiblelibrary]]
        modId="forge"
        mandatory=true
        versionRange="${loader_range}"
        ordering="NONE"
        side="BOTH"

    [[dependencies.theimpossiblelibrary]]
        modId="minecraft"
        mandatory=true
        versionRange="${minecraft_range}"
        ordering="NONE"
        side="BOTH"