//file:noinspection GroovyAssignabilityCheck

/**
 * Common builds and sources relevant to all Forge modules. Based in 1.16.5
 */
buildscript {
    repositories {
        gradlePluginPortal() {
            content {
                unimined_plugin_portal.split(';').each {grp ->
                    includeGroup grp
                }
            }
        }
        maven {
            name = 'WagYourMaven Releases'
            url = uri 'https://maven.wagyourtail.xyz/releases'
            content {
                unimined_releases.split(';').each {grp ->
                    includeGroup grp
                }
            }
        }
        maven {
            name = 'WagYourMaven Snapshots'
            url = uri 'https://maven.wagyourtail.xyz/snapshots'
            content {
                unimined_snapshots.split(';').each {grp ->
                    includeGroup grp
                }
            }
        }
    }
    dependencies {
        classpath "$shadow_plugin:$shadow_version"
        classpath "$unimined_plugin:$unimined_version"
    }
}

apply from: rootProject.file('gradle\\scripts\\java8-module.gradle')

plugins.apply 'xyz.wagyourtail.unimined'

def base = project ':api'

unimined.minecraft {
    version minecraft_1_16_5
    mappings {
        mojmap()
        devFallbackNamespace "official" // ensure the same fallback namespace
    }
    minecraftForge {
        loader forge_1_16_5
    }
    defaultRemapJar = false
}

configurations {
    dev {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    dev jar
}

dependencies {
    api base
}

jar {
    manifest {
        attributes([
                'Implementation-Title': mod_name,
                'Implementation-Version': mod_version
        ])
    }
    mustRunAfter ':api:build'
}

processResources {
    from(base.processResources.outputs) {
        exclude 'fabric.mod.json'
    }
}

processTestResources {
    from base.processTestResources.outputs
}

sourcesJar {
    mustRunAfter ':api:build'
}