/**
 * Common builds and sources relevant to all Forge modules. Based in 1.16.5
 */
plugins {
    alias libs.plugins.unimined
}

extendRunnable()

setDev()

uniminedCore 'forge', false, []

dependencies {
    api project(':api')
}

jar {
    manifest {
        attributes([
                'Implementation-Title': mod_name,
                'Implementation-Version': mod_version
        ])
    }
}

processResources {
    from(getTaskOutputs(project(':api'), 'processResources')) {
        exclude 'fabric.mod.json'
    }
}

processTestResources {
    from getTaskOutputs(project(':api'), 'processTestResources')
}

setJarsRunAfter ':api'