/**
 * Common builds and sources relevant to all Forge modules. Based in 1.16.5
 */
plugins {
    alias libs.plugins.unimined
}

extendRunnable 8
extendFrom 'nonshaded-deps'

uniminedCore 'forge', false, []

setDev()

dependencies {
    api project(':api')
}

jar {
    manifest {
        attributes([
                'Implementation-Title': mod_name,
                'Implementation-Version': mod_version
        ])
    }
}

processResources {
    from(project(':api').processResources.outputs) {
        exclude 'fabric.mod.json'
    }
}

processTestResources {
    from project(':api').processTestResources.outputs
}

setJarsRunAfter true, ':api'