/**
 * Shared implementations for 1.20
 */
plugins {
    alias libs.plugins.shadow
    alias libs.plugins.unimined
}

extendRunnable()

setLoaderConfigs true

setDev()

uniminedCommon()
uniminedFabric false
uniminedForge false
uniminedNeoforge false

setSharedDependencies()

inheritResources ':shared'

setJarsRunAfter ':shared'

relocateCommon()