/**
 * Shared implementations for anything based in 1.21. Compiles against Forge
 */
//file:noinspection GroovyAssignabilityCheck
buildscript {
    repositories {
        gradlePluginPortal() {
            content {
                plugin_portal_content.split(';').each {grp ->
                    includeGroup grp
                }
            }
        }
        maven {
            name = 'Forge'
            url = uri 'https://maven.minecraftforge.net/'
            content {
                forge_content.split(';').each {grp ->
                    includeGroup grp
                }
            }
        }
        maven {
            name = 'ParchmentMC'
            url = uri 'https://maven.parchmentmc.org'
            content {
                parchment_content.split(';').each {grp ->
                    includeGroup grp
                }
            }
        }
    }
    dependencies {
        classpath "$shadow_plugin:$shadow_version"
        classpath "$forge_gradle_plugin:$forge_gradle_version"
        classpath "$parchment_plugin:$parchment_plugin_version"
    }
}

apply from: rootProject.file('gradle\\java21-module.gradle')

plugins.apply 'net.minecraftforge.gradle'
plugins.apply 'org.parchmentmc.librarian.forgegradle'

def base = project ':api'
def shared = project ':shared'

minecraft {
    mappings channel: 'parchment', version: "$parchment_1_21_1-$minecraft_1_21_1"
}

configurations {
    dev {
        canBeResolved = false
        canBeConsumed = true
    }
}

dependencies {
    //noinspection VulnerableLibrariesLocal
    minecraft "$forge_mc:$forge_1_21_1"
    compileOnlyApi base
    compileOnlyApi shared
}

processResources {
    from shared.processResources.outputs
}

processTestResources {
    from shared.processTestResources.outputs
}

jar {
    setArchiveBaseName mod_id
    dependsOn ':shared:build'
}

artifacts {
    dev jar
}