/**
 * Shared implementations for 1.21
 */
plugins {
    alias libs.plugins.unimined
}

extendRunnable()
extendFrom 'nonshaded-deps'

setLoaderConfigs true

setDev()

uniminedCommon()
uniminedFabric false
uniminedForge false
uniminedNeoforge false

setSharedDependencies()

inheritResources ':shared'

setJarsRunAfter false, ':shared'