/**
 * Shared implementations for 1.21
 */
plugins {
    alias libs.plugins.shadow
    id 'project-setup-shared'
}

setupShared([])

tasks.register('genAllSources') {
    dependsOn 'genSources'
    dependsOn 'fabricGenSources'
    dependsOn 'neoforgeGenSources'
    dependsOn ':fabric:genSources'
    dependsOn ':forge:genSources'
    dependsOn ':neoforge:genSources'
}

afterEvaluate {
    it.tasks.genSources {
        mustRunAfter ':fabric:genSources'
        mustRunAfter ':forge:genSources'
        mustRunAfter ':neoforge:genSources'
    }
    it.tasks.fabricGenSources {
        mustRunAfter 'genSources'
    }
    it.tasks.forgeGenSources {
        mustRunAfter 'genSources'
    }
    it.tasks.neoforgeGenSources {
        mustRunAfter 'genSources'
    }
}