//file:noinspection DependencyNotationArgument
//file:noinspection GroovyAssignabilityCheck

/**
 * 1.12.2 forge build
 */

plugins {
    alias libs.plugins.shadow
    alias libs.plugins.unimined
}

extendFrom 'shadow'

uniminedCore 'forge', true, [ dev_arg, common_entrypoint_arg, core_entrypoint_arg ]

setRepositories 'cf', 'ct', 'hei'

dependencies {
    api project(':api')
    api project(':legacy')

    annotationProcessor libs.bundles.legacy.annotations

    compileOnly modsBundle('legacy', 'compile')

    implementation modsBundle('legacy', 'implementation')

    runtimeOnly modsBundle('legacy', 'runtime')
}

inheritCompileSources ':api', ':legacy'

inheritResources ':legacy'

setJarsRunAfter true, ':legacy'

remapJarDefaults

setSharedShadowJar ':api', ':legacy'

tasks.assemble.dependsOn shadowJar