/**
 * Shared implementations for 1.19.4
 */
plugins {
    alias libs.plugins.shadow
    alias libs.plugins.unimined
}

extendFrom 'shadow'

uniminedCommon()
uniminedFabric true
uniminedForge true

setSharedDependencies 'cf', 'ct', 'jei', 'modrinth', 'modmenu'

inheritResources ':shared'

setJarsRunAfter true, ':shared', ':shared_1.19', ':shared_1.19.2'