/**
 * Shared implementations for 1.21.1
 */
plugins {
    alias libs.plugins.shadow
    alias libs.plugins.unimined
}

extendFrom 'shadow'

uniminedCommon()
uniminedFabric true
uniminedForge true
uniminedNeoforge true

setSharedDependencies 'cf', 'ct', 'jei', 'modrinth', 'modmenu', 'pb4'

inheritResources ':shared'

setJarsRunAfter true, ':shared', ':shared_1.21'