buildscript {
    repositories {
        gradlePluginPortal() {
            content {
                plugin_portal_content.split(';').each {grp ->
                    includeGroup grp
                }
            }
        }
        maven {
            name = 'Fabric'
            url = uri 'https://maven.fabricmc.net/'
            content {
                fabric_content.split(';').each {grp ->
                    includeGroup grp
                }
            }
        }
    }
    dependencies {
        classpath "$loom_plugin:$loom_version"
        classpath "$shadow_plugin:$shadow_version"
    }
}

apply from: rootProject.file('gradle\\java17-module.gradle')
apply from: rootProject.file('gradle\\fabric.gradle')

plugins.apply 'fabric-loom'

def base = project ':api'
def fabric = project ':fabric' //TODO Maybe implementation instead of api to clean these up?
def fabric_specific = project ':fabric:fabric_1.20'
def shared = project ':shared:shared_1.20'
def shared_specific = project ':shared:shared_1.20:shared_1.20.4'

def sources = "-Dfabric.classPathGroups=$rootDir\\fabric\\1.20\\1.20.4\\$build_classes;"+
        "$rootDir\\shared\\1.20\\$build_file;$rootDir\\shared\\1.20\\1.20.4\\$build_file"
def args = [ fabric_log_level, dev_arg, sources, common_entrypoint_arg, core_entrypoint_arg ]

[ runClient, runServer ].forEach { it.jvmArgs args}

repositories {
    maven {
        name 'Modrinth'
        url = uri 'https://api.modrinth.com/maven'
        content {
            includeGroup 'maven.modrinth'
        }
    }
    maven {
        name = 'CurseMaven'
        url = uri 'https://www.cursemaven.com'
        content {
            includeGroup 'curse.maven'
        }
    }
    maven {
        name = 'ModMaven'
        url = uri 'https://modmaven.dev'
        content {
            includeGroup 'mezz.jei'
        }
    }
}

dependencies {
    minecraft "$fabric_mc:$minecraft_1_20_4"
    mappings loom.layered() {
        officialMojangMappings()
        parchment "$parchment_data-$minecraft_1_20_4:$parchment_1_20_4@zip"
    }

    compileOnlyApi base
    compileOnlyApi project(path: ':fabric', configuration: 'dev')
    compileOnlyApi fabric_specific
    compileOnlyApi project(path: ':shared:shared_1.20', configuration: 'dev')
    compileOnlyApi project(path: ':shared:shared_1.20:shared_1.20.4', configuration: 'dev')

    modImplementation "$fabric_loader_artifact:$fabric_loader"
    modImplementation "$fabric_api_artifact:$fabric_1_20_4"
    modImplementation "$cloth_artifact:$cloth_1_20_4"
    modImplementation "$configured_artifact:$configured_fabric_1_20_4"
    modImplementation "$modmenu_artifact:$modmenu_1_20_4"
    modImplementation "$serene_seasons_artifact:$serene_seasons_fabric_1_20_4"

    modRuntimeOnly "$jei_artifact:$jei_fabric_1_20_4"
}

remapJar {
    setArchiveBaseName "${mod_id}_remapped"
    inputFile = tasks.shadowJar.archiveFile
}

processResources {
    from fabric_specific.processResources.outputs
}

processTestResources {
    from fabric_specific.processTestResources.outputs
}

compileJava {
    source fabric_specific.sourceSets.main.allJava
}

compileTestJava {
    source fabric_specific.sourceSets.test.allJava
}

jar {
    setArchiveBaseName mod_id
    from(fabric_specific.jar.archiveFile.collect { zipTree it })
}

shadowJar {
    shared_specific.afterEvaluate {
        from shared.sourceSets.main.output.classesDirs.asFileTree
        from it.sourceSets.main.output.classesDirs.asFileTree
        relocate shared_base_package, fabric_base_package
    }
}

tasks.assemble.dependsOn shadowJar
tasks.shadowJar.finalizedBy remapJar
tasks.jar.finalizedBy shadowJar
tasks.compileJava.mustRunAfter ':fabric:fabric_1.20:build'
tasks.compileJava.mustRunAfter ':shared:shared_1.20:shared_1.20.4:build'