/**
 * Shared implementations for 1.20.4
 */
plugins {
    alias libs.plugins.shadow
    alias libs.plugins.unimined
}

extendFrom 'shadow'

uniminedCommon()
uniminedFabric true
uniminedForge true
uniminedNeoforge true

setSharedDependencies false, true, 'cf', 'ct', 'jei', 'modrinth', 'modmenu', 'pb4'

inheritResources ':shared'

def parent_path = getParentPath(name)
setJarsRunAfter false, ':shared', parent_path, "$parent_path:shared_1.20.1"