/**
 * Common base for all legacy builds (pre 1.16)
 */

plugins {
    id 'project-common-functions'
}

/**
 * Only bundled for consolidated warning suppression
 */
@SuppressWarnings(['GrUnresolvedAccess','GrMethodMayBeStatic'])
private void initSetup() {
    setDev()
    setJavaVersion 8
    setJarAndResourceDependency 'api', 'fabric.mod.json', 'META-INF/mods.toml'
    initCommonDeps()
}

initSetup()

dependencies {
    compileOnly project(':api')
}

def replacements = [ 'minecraft_version': libs.versions.minecraft.'1'.'12'.'2'.get(), 'mod_author': mod_authors,
                     'mod_description': mod_description, 'mod_license': mod_license, 'mod_id': mod_id,
                     'mod_name': mod_name, 'mod_version': version ]
//noinspection GrUnresolvedAccess
setResourceReplacements 'mcmod.info', replacements