/**
 * Common base for all legacy builds (pre 1.16)
 */

extendFrom 'shared'

java {
    toolchain.languageVersion = JavaLanguageVersion.of 8
}

setDev()

dependencies {
    compileOnlyApi project(':api')
}

processResources {
    def replacements = [ 'minecraft_version': minecraft_1_12_2, 'mod_author': mod_authors,
                         'mod_description': mod_description, 'mod_license': mod_license, 'mod_id': mod_id,
                         'mod_name': mod_name, 'mod_version': version ]
    inputs.properties replacements
    def parentResources =  getTaskOutputs(project(':api'), 'processResources')
    from(parentResources) {
        exclude 'fabric.mod.json', 'mcmod.info', 'META-INF/mods.toml'
    }
    from(parentResources) {
        include 'mcmod.info'
        expand replacements
    }
}

processTestResources {
    from getTaskOutputs(project(':api'), 'processTestResources')
}

setJarsRunAfter false, ':api'