/**
 * Common base for all legacy builds (pre 1.16)
 */

extendFrom project, 'shared'

java {
    toolchain.languageVersion = JavaLanguageVersion.of 8
}

def base = project ':api'

dependencies {
    compileOnlyApi base
}

processResources {
    def replacements = [ 'minecraft_version': minecraft_1_12_2, 'mod_author': mod_authors,
                         'mod_description': mod_description, 'mod_license': mod_license, 'mod_id': mod_id,
                         'mod_name': mod_name, 'mod_version': version ]
    inputs.properties replacements
    def parentResources = base.processResources.outputs
    from(parentResources) { exclude 'fabric.mod.json', 'mcmod.info', 'META-INF/mods.toml' }
    from(parentResources) {
        include 'mcmod.info'
        expand replacements
    }
}

processTestResources {
    from base.processTestResources.outputs
}

tasks.jar.dependsOn ':api:build'

subprojects { sub ->
    extendRunnable sub, 'cleanroom'==sub.name ? 21 : 8
    repositories {
        maven {
            name = 'CleanroomMC'
            url = uri 'https://maven.cleanroommc.com'
            content {
                includeGroup 'mezz'
            }
        }
        maven {
            name = 'CurseMaven'
            url = uri 'https://curse.cleanroommc.com/'
            content {
                includeGroup 'curse.maven'
            }
        }
        maven {
            name = 'BlameJared'
            url = uri 'https://maven.blamejared.com'
            content {
                [ 'bookshelf', 'gamestages' ].forEach {grp ->
                    includeGroup "net.darkhax.$grp"
                }
            }
        }
    }
    def legacy_base = project ':legacy'
    dependencies {
        api base
        api legacy_base

        annotationProcessor libs.bundles.legacy.annotations
        compileOnly modsBundle(sub, 'legacy', 'compile')
        implementation modsBundle(sub, 'legacy', 'implementation')
        runtimeOnly modsBundle(sub, 'legacy', 'runtime')
    }
    compileJava {
        source base.sourceSets.main.allJava, legacy_base.sourceSets.main.allJava
    }
    compileTestJava {
        source base.sourceSets.test.allJava, legacy_base.sourceSets.test.allJava
    }
    processResources {
        from legacy_base.processResources.outputs
    }
    processTestResources {
        from legacy_base.processTestResources.outputs
    }
    jar {
        from(legacy_base.jar.archiveFile.collect { zipTree it })
        manifest {
            attributes([
                    'FMLCorePlugin': legacy_entrypoint,
                    'FMLCorePluginContainsFMLMod': true,
                    'ForceLoadAsMod': true,
                    'Implementation-Title': mod_name,
                    'Implementation-Version': mod_version
            ])
        }
        finalizedBy 'shadowJar'
        dependsOn ':legacy:build'
    }
}