/**
 * Pass through parent module for shared version modules
 */

plugins {
    id 'project-setup-common'
}

evaluationDependsOn ':api'
evaluationDependsOn ':fabric'
evaluationDependsOn ':forge'

//noinspection GrUnresolvedAccess
initJavaPlugin()

setDev()

//noinspection GrUnresolvedAccess
setJarAndResourceDependency 'api'