/**
 * Pass through parent module for shared version modules
 */

plugins {
    id 'project-setup-common'
}

evaluationDependsOn ':api'
evaluationDependsOn ':fabric'
evaluationDependsOn ':forge'

//noinspection GrUnresolvedAccess
initJavaPlugin()
createResourceArtifact()
createClassConfigs false, true

//noinspection GrUnresolvedAccess
addParentProcessedResources()

dependencies {
    compileOnly project(':api')
}

tasks.compileJava.mustRunAfter ':api:classes'