/**
 * Common builds and sources relevant to all NeoForge modules. Based in 1.20.4
 */
plugins {
    alias libs.plugins.unimined
    alias libs.plugins.shadow
}

extendRunnable project, 17

uniminedCore project, 'neoforge', false, []

setDev

dependencies {
    api project(':api')
}

jar {
    from(project(':api').jar.archiveFile.collect {entry ->
        zipTree entry
    })
    manifest {
        attributes([
                'Implementation-Title': mod_name,
                'Implementation-Version': mod_version
        ])
    }
}

setJarsRunAfter false, ':api', ':shared'