/**
 * Shared implementations for 1.18
 */
plugins {
    alias libs.plugins.unimined
}

extendRunnable()

setLoaderConfigs false

uniminedCommon()
uniminedFabric true
uniminedForge true

setSharedDependencies 'cf', 'ct', 'jei', 'modrinth', 'modmenu'

inheritResources ':shared'

setJarsRunAfter ':shared'