/**
 * Shared implementations for 1.20.1
 */
plugins {
    alias libs.plugins.shadow
    id 'project-setup-shared'
}

setupShared([])

tasks.register('genAllSources') {
    dependsOn 'genSources'
    dependsOn 'fabricGenSources'
    dependsOn 'forgeGenSources'
}

afterEvaluate {
    it.tasks.genSources {
        dependsOn ':shared:shared_1.16:genAllSources'
        dependsOn ':shared:shared_1.18:genAllSources'
        dependsOn ':shared:shared_1.19:genAllSources'
        dependsOn ':shared:shared_1.20:genAllSources'
        dependsOn ':shared:shared_1.21:genAllSources'
    }
    it.tasks.fabricGenSources {
        mustRunAfter 'genSources'
    }
    it.tasks.forgeGenSources {
        mustRunAfter 'genSources'
    }
}