/**
 * Shared implementations for 1.20.1
 */
plugins {
    alias libs.plugins.shadow
    alias libs.plugins.unimined
}

extendRunnable()
extendFrom 'shadow'

setLoaderConfigs false

uniminedCommon()
uniminedFabric true
uniminedForge true

setSharedDependencies 'cf', 'ct', 'jei', 'modrinth', 'modmenu'

inheritResources ':shared'

setJarsRunAfter true, ':shared', ':shared_1.20'