/**
 * NeoForge implementation for 1.21. Based in 1.21.1
 */
//file:noinspection GroovyAssignabilityCheck
buildscript {
    repositories {
        gradlePluginPortal() {
            content {
                plugin_portal_content.split(';').each {grp ->
                    includeGroup grp
                }
            }
        }
        maven {
            name = 'NeoForge'
            url = uri 'https://maven.neoforged.net/releases'
            content {
                neoforge_content.split(';').each {grp ->
                    includeGroup grp
                }
            }
        }
    }
    dependencies {
        classpath "$shadow_plugin:$shadow_version"
        classpath "$neoforge_gradle_plugin:$neoforge_gradle_version"
    }
}

apply from: rootProject.file('gradle\\java21-module.gradle')

plugins.apply 'net.neoforged.gradle.userdev'

def base = project ':api'
def neoforge = project ':neoforge'

subsystems {
    parchment {
        minecraftVersion = minecraft_1_21_1
        mappingsVersion = parchment_1_21_1
    }
}

configurations {
    dev {
        canBeResolved = false
        canBeConsumed = true
    }
}

dependencies {
    //noinspection VulnerableLibrariesLocal
    implementation "$neoforge_mc:$neoforge_1_21_1"

    compileOnlyApi base
    compileOnlyApi project(path: ':neoforge', configuration: 'dev')
    compileOnlyApi project(path: ':shared:shared_1.21', configuration: 'dev')
}

processResources {
    from neoforge.processResources.outputs
}

processTestResources {
    from neoforge.processTestResources.outputs
}

jar {
    from(neoforge.jar.archiveFile.collect { zipTree(it) })
    manifest {
        attributes([
                'Implementation-Version': mod_version
        ])
    }
}

artifacts {
    dev jar
}

tasks.classes.mustRunAfter ':shared:shared_1.21:reobfJar'
tasks.classes.mustRunAfter ':neoforge:jar'
afterEvaluate {
    [ 'cacheVersionManifest1.21.1', 'neoFormUnzipAdditionalSources', 'neoFormListLibraries' ].forEach {
        tasks.named(it).get().mustRunAfter ':neoforge:neoforge_1.20:neoforge_1.20.6:idePostSync'
    }
}