//file:noinspection GroovyAssignabilityCheck
buildscript {
    repositories {
        gradlePluginPortal() {
            content {
                [ 'com.fasterxml', 'com.fasterxml.jackson', 'com.fasterxml.woodstox', 'com.google.code.findbugs',
                  'com.google.code.gson', 'com.google.errorprone', 'com.google.guava', 'com.google.j2objc',
                  'com.machinezoo.noexception', 'commons-codec', 'commons-io', 'commons-logging', 'de.siegmar',
                  'io.fabric8', 'io.github.goooler.shadow', 'io.netty', 'it.unimi.dsi', 'jakarta.platform',
                  'net.sf.jopt-simple', 'org.apache', 'org.apache.ant', 'org.apache.commons',
                  'org.apache.httpcomponents', 'org.apache.logging', 'org.apache.logging.log4j', 'org.apache.maven',
                  'org.checkerframework', 'org.codehaus.groovy', 'org.codehaus.plexus', 'org.codehaus.woodstox',
                  'org.eclipse.ee4j', 'org.eclipse.jetty', 'org.jdom', 'org.junit', 'org.mockito', 'org.ow2',
                  'org.ow2.asm', 'org.slf4j', 'org.sonatype.oss', 'org.springframework', 'org.tukaani',
                  'org.vafer' ].forEach { includeGroup it }
            }
        }
        maven {
            name = 'Forge'
            url = uri('https://maven.minecraftforge.net/')
            content {
                [ 'net.minecraftforge', 'net.minecraftforge.gradle' ].forEach{ includeGroup it }
            }
        }
        maven {
            name = 'ParchmentMC'
            url = uri('https://maven.parchmentmc.org')
            content {
                [ 'org.parchmentmc', 'org.parchmentmc.feather',
                  'org.parchmentmc.librarian.forgegradle' ].forEach { includeGroup it }
            }
        }
    }
    dependencies {
        classpath("$shadow_plugin:$shadow_version")
        classpath("$forge_gradle_plugin:$forge_gradle_version")
        classpath("$parchment_plugin:$parchment_plugin_version")
    }
}

apply from: rootProject.file('gradle\\java17-module.gradle')
apply from: rootProject.file('gradle\\shadow-relocate.gradle')
apply from: rootProject.file('gradle\\forgemap-to-mojmap.gradle')

plugins.apply 'net.minecraftforge.gradle'
plugins.apply 'org.parchmentmc.librarian.forgegradle'

def base = project ':api'
def forge = project ':forge'
def shared = project ':shared:1.18'

def classpath_file = "${mod_id}-${mod_version}_mapped_parchment_$parchment_1_18_2-${minecraft_1_18_2}.jar"

minecraft {
    copyIdeResources = true
    mappings channel: 'parchment', version: "$parchment_1_18_2-$minecraft_1_18_2"
    runs {
        def runSources = [ sourceSets.main ]
        def args = [ dev_arg, "$classpath_arg$classpath_file".toString(), common_entrypoint_arg, core_entrypoint_arg ]
        configureEach {
            def srgToMcpFile = project.tasks.createSrgToMcp.outputs.files[0].path
            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.console.level', forge_log_level
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', srgToMcpFile
            property 'net.minecraftforge.gradle.GradleStart.srg.srg-mcp', srgToMcpFile
            setSources runSources
            jvmArgs args
        }
        client {
            workingDirectory file('run_client')
        }
        server {
            workingDirectory file('run_server')
        }
    }
}

repositories {
    maven {
        name = 'BlameJared'
        url = uri('https://maven.blamejared.com')
        content {
            [ 'bookshelf', 'gamestages' ].forEach {includeGroup "net.darkhax.${it}"}
        }
    }
    maven {
        name = 'CurseMaven'
        url = uri('https://www.cursemaven.com')
        content {
            includeGroup 'curse.maven'
        }
    }
    maven {
        name = 'ModMaven'
        url = uri('https://modmaven.dev')
        content {
            includeGroup 'mezz.jei'
        }
    }
    flatDir {
        dirs "$projectDir/build/libs"
    }
}

dependencies {
    //noinspection VulnerableLibrariesLocal
    minecraft "$forge_mc:$forge_1_18_2"

    compileOnlyApi base
    compileOnlyApi project(path: ':forge', configuration: 'dev')
    compileOnlyApi shared

    //mod support dependencies
    implementation fg.deobf("$blueskies_artifact:$blueskies_1_18_2")
    implementation fg.deobf("$bookshelf_artifact-$bookshelf_forge_1_18_2")
    implementation fg.deobf("$champions_artifact:$champions_1_18_2")
    implementation fg.deobf("$configured_artifact:$configured_1_18_2")
    implementation fg.deobf("$coroutil_artifact:$coroutil_forge_1_18_2")
    implementation fg.deobf("$enhanced_celestials_artifact:$enhanced_celestials_1_18_2")
    implementation fg.deobf("$infernal_mobs_artifact:$infernal_mobs_1_18_2")
    implementation fg.deobf("$game_stages_artifact-$game_stages_1_18_2")
    implementation fg.deobf("$serene_seasons_artifact:$serene_seasons_1_18_2")
    implementation fg.deobf("$structure_gel_api_artifact:$structure_gel_api_1_18_2")
    implementation fg.deobf("$weather2_artifact:$weather2_1_18_2")

    runtimeOnly fg.deobf("$jei_artifact:$jei_forge_1_18_2")
    runtimeOnly fg.deobf("mods.thecomputerizer.theimpossiblelibrary:theimpossiblelibrary:$mod_version")
}

reobf {
    shadowJar {
        dependsOn createMcpToSrg
        mappings = createMcpToSrg.output
    }
}

jar {
    manifest {
        attributes([
                'Implementation-Version': mod_version
        ])
    }
}

static Map<String,String> getRemaps(String toRemap) {
    Map<String,String> map = new HashMap<>()
    toRemap.split(',').each {
        def split = it.split(':')
        map.put(split[0],split[1])
    }
    return map
}

shadowJar {
    [ base, forge ].forEach {
        from(it.jar.archiveFile.collect { zipTree(it) })
    }
    getRemaps(basic_remaps).forEach((key,value) -> relocate "net.minecraft.${key}", "net.minecraft.${value}")
    getRemaps(render_remaps).forEach((key,value) -> relocate key, "com.mojang.${value}")
    shared.afterEvaluate {
        from(it.jar.archiveFile.collect { zipTree(it) })
        relocate shared_base_package, forge_base_package
    }
}

tasks.assemble.dependsOn shadowJar
tasks.shadowJar.dependsOn 'reobfJar'
tasks.jar.finalizedBy 'reobfJar'
tasks.jar.dependsOn ':forge:build'