/**
 * Base project for the main API & any version-agnostic code that isn't modloader-specific
 */

plugins {
    id 'project-setup-common'
}

initJavaPlugin()
createResourceArtifact()

createClassConfigs false, true

injectConstants()

initDependencies()

setCommonRepositories([ 'central', 'fast' ])

dependencies {
    //noinspection DependencyNotationArgument
    compileOnly(libs.bundles.api.compile) {
        exclude group: 'com.github.spotbugs'
    }
    //noinspection DependencyNotationArgument
    compileOnly libs.spotbugs.annotations
}

processResources {
    from sourceSets.main.resources.srcDirs
}

plugins.apply 'source-helpers'
setupJarGraphs()

def injectConstants() {
    def path = "api/src/main/java/${ "${api_package}.core.TILRef".replace '.', '/'}.java"
    def target = file("${rootProject.projectDir}/$path")
    def replacements = [ 'MODID = "': "MODID = \"$mod_id\";",
                         'NAME ="': "NAME = \"$mod_name\";",
                         'VERSION = "': "VERSION = \"$mod_version\";" ]
    List<String> lines = new ArrayList<>()
    target.eachLine { line ->
        //noinspection GroovyMissingReturnStatement
        replacements.each {entry ->
            String key = entry.key
            if(line.contains(key)) {
                int index = line.indexOf key
                line = "${line.substring(0,index)}${entry.value}"
            }
        }
        lines.add line
    }
    target.withWriter {writer ->
        lines.forEach {line ->
            writer.writeLine line
        }
    }
}