apply from: rootProject.file('shared.gradle')
apply from: rootProject.file('gradle\\lombok.gradle')

java {
    toolchain.languageVersion = JavaLanguageVersion.of 8
}

repositories {
    mavenCentral()
    maven {
        name = 'SonaType'
        url = uri 'https://oss.sonatype.org/content/repositories/public/'
        content {
            includeGroup 'it.unimi.dsi'
        }
    }
}

configurations {
    dev {
        canBeResolved = false
        canBeConsumed = true
    }
}

dependencies {
    compileOnly "$jsr_artifact:$jsr_version"
    //noinspection VulnerableLibrariesLocal
    compileOnly "io.netty:netty-all:$netty_version" //Not shaded so vulnerable dependecies aren't an issue
    compileOnly "it.unimi.dsi:fastutil:$fast_version"
    compileOnly "$log4j_artifact:$log4j_version"
    compileOnly "org.ow2.asm:asm-commons:$asm_version"
    compileOnly "org.ow2.asm:asm-util:$asm_version"

    implementation "$burningwave_group:$burningwave_name:$burningwave_version"
    implementation "$burningwave_group:$burningwave_driver_name:$burningwave_driver_version"
    implementation "$toolfactory_group:$toolfactory_name:$toolfactory_version"
}

processResources {
    from sourceSets.main.resources.srcDirs
}

artifacts {
    dev jar
}