import static org.gradle.api.logging.LogLevel.INFO
import static org.gradle.api.logging.LogLevel.QUIET

/**
 * NeoForge implementation for 1.20.4
 */
//file:noinspection GroovyAssignabilityCheck
buildscript {
    repositories {
        gradlePluginPortal() {
            content {
                unimined_plugin_portal.split(';').each {grp ->
                    includeGroup grp
                }
            }
        }
        maven {
            name = 'WagYourMaven Releases'
            url = uri 'https://maven.wagyourtail.xyz/releases'
            content {
                unimined_releases.split(';').each {grp ->
                    includeGroup grp
                }
            }
        }
        maven {
            name = 'WagYourMaven Snapshots'
            url = uri 'https://maven.wagyourtail.xyz/snapshots'
            content {
                unimined_snapshots.split(';').each {grp ->
                    includeGroup grp
                }
            }
        }
    }
    dependencies {
        classpath "$shadow_plugin:$shadow_version"
        classpath "$unimined_plugin:$unimined_version"
    }
}

apply from: rootProject.file('gradle\\java17-module.gradle')

plugins.apply 'xyz.wagyourtail.unimined'

def base = project ':api'
def neoforge = project ':neoforge'
def neoforge_specific = project ':neoforge:neoforge_1.20'
def shared = project ':shared:shared_1.20'
def shared_specific = project ':shared:shared_1.20:shared_1.20.4'

unimined.minecraft {
    version minecraft_1_20_4
    mappings {
        parchment parchment_1_20_4
    }
    neoForge {
        loader neoforge_1_20_4
        runs.auth.username = minecraft_username
        runs.all {
            systemProperty 'foundation.verbose', 'true'
            return
        }
    }
}

repositories {
    maven {
        name = 'CurseMaven'
        url = uri 'https://curse.cleanroommc.com/'
        content {
            includeGroup 'curse.maven'
        }
    }
    maven {
        name = 'ModMaven'
        url = uri 'https://modmaven.dev'
        content {
            includeGroup 'mezz.jei'
        }
    }
}

dependencies {
    compileOnlyApi base
    compileOnlyApi project(path: ':neoforge', configuration: 'dev')
    compileOnlyApi neoforge_specific
    compileOnlyApi shared
    compileOnlyApi shared_specific

    //mod support dependencies
    implementation "$configured_artifact:$configured_neoforge_1_20_4"
    implementation "$infernal_mobs_artifact:$infernal_mobs_neoforge_1_20_4"
    implementation "$serene_seasons_artifact:$serene_seasons_neoforge_1_20_4"

    runtimeOnly "$glitchcore_artifact:$glitchcore_neoforge_1_20_4"
    runtimeOnly "$jei_artifact:$jei_neoforge_1_20_4"
}

processResources {
    from neoforge_specific.processResources.outputs
}

processTestResources {
    from neoforge_specific.processTestResources.outputs
}

jar {
    manifest {
        attributes([
                'Implementation-Version': mod_version
        ])
    }
    finalizedBy shadowJar
    mustRunAfter ':neoforge:neoforge_1.20:build'
    mustRunAfter ':shared:shared_1.20:shared_1.20.4:build'
}

sourcesJar {
    mustRunAfter ':neoforge:neoforge_1.20:build'
    mustRunAfter ':shared:shared_1.20:shared_1.20.4:build'
}

shadowJar {
    shared_specific.afterEvaluate {
        from shared.sourceSets.main.output.classesDirs.asFileTree
        from it.sourceSets.main.output.classesDirs.asFileTree
        from neoforge.sourceSets.main.output.classesDirs.asFileTree
        from neoforge_specific.sourceSets.main.output.classesDirs.asFileTree
        relocate "${neoforge_base_package}.client.event.events", "${neoforge_1_20_4_package}.client.event.events"
        relocate "${neoforge_base_package}.common.event.events", "${neoforge_1_20_4_package}.common.event.events"
        relocate shared_base_package, neoforge_base_package
    }
}

tasks.remapJar {
    doFirst {
        logging.captureStandardOutput INFO
    }
    doLast {
        logging.captureStandardOutput QUIET
    }
}