//file:noinspection GroovyAssignabilityCheck

/**
 * Shared implementations for 1.20.6
 */
apply from: rootProject.file('gradle\\scripts\\java21-module.gradle')

unimined.minecraft {
    version minecraft_1_20_6
    mappings {
        mojmap()
        devFallbackNamespace 'official'
    }
}

unimined.minecraft(sourceSets.fabric) {
    combineWith sourceSets.main
    fabric {
        loader fabric_loader
        runs.all {
            systemProperty 'foundation.verbose', 'true'
            return
        }
    }
}

unimined.minecraft(sourceSets.forge) {
    combineWith sourceSets.main
    minecraftForge {
        loader forge_1_20_6
        runs.all {
            systemProperty 'foundation.verbose', 'true'
            return
        }
    }
}

unimined.minecraft(sourceSets.neoforge) {
    combineWith sourceSets.main
    neoForge {
        loader neoforge_1_20_6
        runs.all {
            systemProperty 'foundation.verbose', 'true'
            return
        }
    }
}

def base = project ':api'
def fabric_base = project ':fabric'
def forge_base = project ':forge'
def neoforge_base = project ':neoforge'
def shared = project ':shared'
def shared_specific = project ':shared:shared_1.20'

repositories {
    maven {
        name = 'CurseMaven'
        url = uri 'https://curse.cleanroommc.com/'
        content {
            includeGroup 'curse.maven'
        }
    }
    maven {
        name = 'BlameJared'
        url = uri 'https://maven.blamejared.com'
        content {
            [ 'bookshelf', 'gamestages' ].forEach {
                includeGroup "net.darkhax.$it"
            }
        }
    }
    maven {
        name = 'ModMaven'
        url = uri 'https://modmaven.dev'
        content {
            includeGroup 'mezz.jei'
        }
    }
    maven {
        name 'Modrinth'
        url = uri 'https://api.modrinth.com/maven'
        content {
            includeGroup 'maven.modrinth'
        }
    }
}

dependencies {
    //common dependencies
    compileOnlyApi base
    compileOnlyApi shared
    compileOnlyApi project(path: ':shared:shared_1.20', configuration: 'dev')

    //fabric dependencies
    fabricCompileOnly project(path: ':fabric', configuration: 'dev')
    buildModDependencies('fabric', '20_6').each {mod ->
        fabricImplementation mod
    }
    fabricRuntimeOnly "$architectury_artifact:$architectury_fabric_1_20_6"
    fabricRuntimeOnly "$jei_artifact:$jei_fabric_1_20_6"

    //forge dependencies
    forgeCompileOnly project(path: ':forge', configuration: 'dev')
    buildModDependencies('forge', '20_6').each {mod ->
        forgeImplementation mod
    }
    forgeRuntimeOnly "$jei_artifact:$jei_forge_1_20_6"

    //neoorge dependencies
    neoforgeCompileOnly project(path: ':neoforge', configuration: 'dev')
    buildModDependencies('neoforge', '20_6').each {mod ->
        neoforgeImplementation mod
    }
    neoforgeRuntimeOnly "$jei_artifact:$jei_neoforge_1_20_6"
}

jar {
    manifest {
        attributes([
                'Implementation-Version': mod_version
        ])
    }
    finalizedBy shadowJar
    mustRunAfter ':shared:build'
    mustRunAfter ':shared:shared_1.20:build'
    mustRunAfter ':shared:shared_1.20:shared_1.20.4:build'
}


processResources {
    from shared.processResources.outputs
}

processTestResources {
    from shared.processTestResources.outputs
}

shadowJar {
    [ base, fabric_base, forge_base, neoforge_base, shared, shared_specific ].forEach {
        from(it.jar.archiveFile.collect { zipTree it })
    }
    shadowJar.finalizedBy remapJar
}

sourcesJar {
    mustRunAfter ':shared:build'
    mustRunAfter ':shared:shared_1.20:build'
    mustRunAfter ':shared:shared_1.20:shared_1.20.4:build'
}

tasks.assemble.dependsOn shadowJar