//file:noinspection GroovyAssignabilityCheck

/**
 * Shared implementations for 1.20.6
 */
plugins {
    alias libs.plugins.shadow
    alias libs.plugins.unimined
}

extendFrom project, 'shadow'

uniminedCommon project
uniminedFabric project, true
uniminedForge project, true
uniminedNeoforge project, true

repositories {
    maven {
        name = 'Nucleoid'
        url = uri 'https://maven.nucleoid.xyz/'
        content {
            includeGroup 'eu.pb4'
        }
    }
}

jar {
    mustRunAfter ':shared:shared_1.20:shared_1.20.4:build'
}

sourcesJar {
    mustRunAfter ':shared:shared_1.20:shared_1.20.4:build'
}